// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package gauge_messages is a generated protocol buffer package.

It is generated from these files:
	api.proto
	api_v2.proto
	messages.proto
	spec.proto

It has these top-level messages:
	GetProjectRootRequest
	GetProjectRootResponse
	GetInstallationRootRequest
	GetInstallationRootResponse
	GetAllStepsRequest
	GetAllStepsResponse
	GetAllSpecsRequest
	GetAllSpecsResponse
	GetAllConceptsRequest
	GetAllConceptsResponse
	ConceptInfo
	GetStepValueRequest
	GetStepValueResponse
	GetLanguagePluginLibPathRequest
	GetLanguagePluginLibPathResponse
	ErrorResponse
	PerformRefactoringRequest
	PerformRefactoringResponse
	ExtractConceptInfoRequest
	ExtractConceptRequest
	TextInfo
	Step
	ExtractConceptResponse
	FormatSpecsRequest
	FormatSpecsResponse
	UnsupportedApiMessageResponse
	APIMessage
	ExecutionRequest
	Result
	ExecutionResponse
	KillProcessRequest
	ExecutionStatusResponse
	ExecutionStartingRequest
	ExecutionEndingRequest
	SpecExecutionStartingRequest
	SpecExecutionEndingRequest
	ScenarioExecutionStartingRequest
	ScenarioExecutionEndingRequest
	StepExecutionStartingRequest
	StepExecutionEndingRequest
	ExecutionInfo
	SpecInfo
	ScenarioInfo
	StepInfo
	ExecuteStepRequest
	StepValidateRequest
	StepValidateResponse
	SuiteExecutionResult
	StepNamesRequest
	StepNamesResponse
	ScenarioDataStoreInitRequest
	SpecDataStoreInitRequest
	SuiteDataStoreInitRequest
	ParameterPosition
	RefactorRequest
	RefactorResponse
	StepNameRequest
	StepNameResponse
	UnsupportedMessageResponse
	Message
	ProtoSpec
	ProtoItem
	ProtoScenario
	Span
	ProtoTableDrivenScenario
	ProtoStep
	ProtoConcept
	ProtoTags
	Fragment
	Parameter
	ProtoComment
	ProtoTable
	ProtoTableRow
	ProtoStepExecutionResult
	ProtoExecutionResult
	ProtoHookFailure
	ProtoSuiteResult
	ProtoSpecResult
	ProtoStepValue
*/
package gauge_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIMessage_APIMessageType int32

const (
	APIMessage_GetProjectRootRequest            APIMessage_APIMessageType = 1
	APIMessage_GetProjectRootResponse           APIMessage_APIMessageType = 2
	APIMessage_GetInstallationRootRequest       APIMessage_APIMessageType = 3
	APIMessage_GetInstallationRootResponse      APIMessage_APIMessageType = 4
	APIMessage_GetAllStepsRequest               APIMessage_APIMessageType = 5
	APIMessage_GetAllStepResponse               APIMessage_APIMessageType = 6
	APIMessage_GetAllSpecsRequest               APIMessage_APIMessageType = 7
	APIMessage_GetAllSpecsResponse              APIMessage_APIMessageType = 8
	APIMessage_GetStepValueRequest              APIMessage_APIMessageType = 9
	APIMessage_GetStepValueResponse             APIMessage_APIMessageType = 10
	APIMessage_GetLanguagePluginLibPathRequest  APIMessage_APIMessageType = 11
	APIMessage_GetLanguagePluginLibPathResponse APIMessage_APIMessageType = 12
	APIMessage_ErrorResponse                    APIMessage_APIMessageType = 13
	APIMessage_GetAllConceptsRequest            APIMessage_APIMessageType = 14
	APIMessage_GetAllConceptsResponse           APIMessage_APIMessageType = 15
	APIMessage_PerformRefactoringRequest        APIMessage_APIMessageType = 16
	APIMessage_PerformRefactoringResponse       APIMessage_APIMessageType = 17
	APIMessage_ExtractConceptRequest            APIMessage_APIMessageType = 18
	APIMessage_ExtractConceptResponse           APIMessage_APIMessageType = 19
	APIMessage_FormatSpecsRequest               APIMessage_APIMessageType = 20
	APIMessage_FormatSpecsResponse              APIMessage_APIMessageType = 21
	APIMessage_UnsupportedApiMessageResponse    APIMessage_APIMessageType = 22
)

var APIMessage_APIMessageType_name = map[int32]string{
	1:  "GetProjectRootRequest",
	2:  "GetProjectRootResponse",
	3:  "GetInstallationRootRequest",
	4:  "GetInstallationRootResponse",
	5:  "GetAllStepsRequest",
	6:  "GetAllStepResponse",
	7:  "GetAllSpecsRequest",
	8:  "GetAllSpecsResponse",
	9:  "GetStepValueRequest",
	10: "GetStepValueResponse",
	11: "GetLanguagePluginLibPathRequest",
	12: "GetLanguagePluginLibPathResponse",
	13: "ErrorResponse",
	14: "GetAllConceptsRequest",
	15: "GetAllConceptsResponse",
	16: "PerformRefactoringRequest",
	17: "PerformRefactoringResponse",
	18: "ExtractConceptRequest",
	19: "ExtractConceptResponse",
	20: "FormatSpecsRequest",
	21: "FormatSpecsResponse",
	22: "UnsupportedApiMessageResponse",
}
var APIMessage_APIMessageType_value = map[string]int32{
	"GetProjectRootRequest":            1,
	"GetProjectRootResponse":           2,
	"GetInstallationRootRequest":       3,
	"GetInstallationRootResponse":      4,
	"GetAllStepsRequest":               5,
	"GetAllStepResponse":               6,
	"GetAllSpecsRequest":               7,
	"GetAllSpecsResponse":              8,
	"GetStepValueRequest":              9,
	"GetStepValueResponse":             10,
	"GetLanguagePluginLibPathRequest":  11,
	"GetLanguagePluginLibPathResponse": 12,
	"ErrorResponse":                    13,
	"GetAllConceptsRequest":            14,
	"GetAllConceptsResponse":           15,
	"PerformRefactoringRequest":        16,
	"PerformRefactoringResponse":       17,
	"ExtractConceptRequest":            18,
	"ExtractConceptResponse":           19,
	"FormatSpecsRequest":               20,
	"FormatSpecsResponse":              21,
	"UnsupportedApiMessageResponse":    22,
}

func (x APIMessage_APIMessageType) Enum() *APIMessage_APIMessageType {
	p := new(APIMessage_APIMessageType)
	*p = x
	return p
}
func (x APIMessage_APIMessageType) String() string {
	return proto.EnumName(APIMessage_APIMessageType_name, int32(x))
}
func (x *APIMessage_APIMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(APIMessage_APIMessageType_value, data, "APIMessage_APIMessageType")
	if err != nil {
		return err
	}
	*x = APIMessage_APIMessageType(value)
	return nil
}
func (APIMessage_APIMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{26, 0}
}

// / Request to get the Root Directory of the project
type GetProjectRootRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetProjectRootRequest) Reset()                    { *m = GetProjectRootRequest{} }
func (m *GetProjectRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRootRequest) ProtoMessage()               {}
func (*GetProjectRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// / Response of GetProjectRootRequest.
type GetProjectRootResponse struct {
	// / Holds the absolute path of the Project Root directory.
	ProjectRoot      *string `protobuf:"bytes,1,req,name=projectRoot" json:"projectRoot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetProjectRootResponse) Reset()                    { *m = GetProjectRootResponse{} }
func (m *GetProjectRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRootResponse) ProtoMessage()               {}
func (*GetProjectRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetProjectRootResponse) GetProjectRoot() string {
	if m != nil && m.ProjectRoot != nil {
		return *m.ProjectRoot
	}
	return ""
}

// / Request to get the Root Directory of the Gauge installation
type GetInstallationRootRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetInstallationRootRequest) Reset()                    { *m = GetInstallationRootRequest{} }
func (m *GetInstallationRootRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInstallationRootRequest) ProtoMessage()               {}
func (*GetInstallationRootRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// / Response of GetInstallationRootRequest
type GetInstallationRootResponse struct {
	// / Holds the absolute path of the Gauge installation directory
	InstallationRoot *string `protobuf:"bytes,1,req,name=installationRoot" json:"installationRoot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetInstallationRootResponse) Reset()                    { *m = GetInstallationRootResponse{} }
func (m *GetInstallationRootResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInstallationRootResponse) ProtoMessage()               {}
func (*GetInstallationRootResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetInstallationRootResponse) GetInstallationRoot() string {
	if m != nil && m.InstallationRoot != nil {
		return *m.InstallationRoot
	}
	return ""
}

// / Request to get all Steps in the project
type GetAllStepsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllStepsRequest) Reset()                    { *m = GetAllStepsRequest{} }
func (m *GetAllStepsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllStepsRequest) ProtoMessage()               {}
func (*GetAllStepsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// / Response to GetAllStepsRequest
type GetAllStepsResponse struct {
	// / Holds a collection of Steps that are defined in the project.
	AllSteps         []*ProtoStepValue `protobuf:"bytes,1,rep,name=allSteps" json:"allSteps,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetAllStepsResponse) Reset()                    { *m = GetAllStepsResponse{} }
func (m *GetAllStepsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllStepsResponse) ProtoMessage()               {}
func (*GetAllStepsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetAllStepsResponse) GetAllSteps() []*ProtoStepValue {
	if m != nil {
		return m.AllSteps
	}
	return nil
}

// / Request to get all Specs in the project
type GetAllSpecsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllSpecsRequest) Reset()                    { *m = GetAllSpecsRequest{} }
func (m *GetAllSpecsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllSpecsRequest) ProtoMessage()               {}
func (*GetAllSpecsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// / Response to GetAllSpecsRequest
type GetAllSpecsResponse struct {
	// / Holds a collection of Specs that are defined in the project.
	Specs            []*ProtoSpec `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetAllSpecsResponse) Reset()                    { *m = GetAllSpecsResponse{} }
func (m *GetAllSpecsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllSpecsResponse) ProtoMessage()               {}
func (*GetAllSpecsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetAllSpecsResponse) GetSpecs() []*ProtoSpec {
	if m != nil {
		return m.Specs
	}
	return nil
}

// / Request to get all Concepts in the project
type GetAllConceptsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAllConceptsRequest) Reset()                    { *m = GetAllConceptsRequest{} }
func (m *GetAllConceptsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllConceptsRequest) ProtoMessage()               {}
func (*GetAllConceptsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// / Response to GetAllConceptsResponse
type GetAllConceptsResponse struct {
	// / Holds a collection of Concepts that are defined in the project.
	Concepts         []*ConceptInfo `protobuf:"bytes,1,rep,name=concepts" json:"concepts,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetAllConceptsResponse) Reset()                    { *m = GetAllConceptsResponse{} }
func (m *GetAllConceptsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllConceptsResponse) ProtoMessage()               {}
func (*GetAllConceptsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetAllConceptsResponse) GetConcepts() []*ConceptInfo {
	if m != nil {
		return m.Concepts
	}
	return nil
}

// / Details of a Concept
type ConceptInfo struct {
	// / The text that defines a concept
	StepValue *ProtoStepValue `protobuf:"bytes,1,req,name=stepValue" json:"stepValue,omitempty"`
	// / The absolute path to the file that contains the Concept
	Filepath *string `protobuf:"bytes,2,req,name=filepath" json:"filepath,omitempty"`
	// / The line number in the file where the concept is defined.
	LineNumber       *int32 `protobuf:"varint,3,req,name=lineNumber" json:"lineNumber,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConceptInfo) Reset()                    { *m = ConceptInfo{} }
func (m *ConceptInfo) String() string            { return proto.CompactTextString(m) }
func (*ConceptInfo) ProtoMessage()               {}
func (*ConceptInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ConceptInfo) GetStepValue() *ProtoStepValue {
	if m != nil {
		return m.StepValue
	}
	return nil
}

func (m *ConceptInfo) GetFilepath() string {
	if m != nil && m.Filepath != nil {
		return *m.Filepath
	}
	return ""
}

func (m *ConceptInfo) GetLineNumber() int32 {
	if m != nil && m.LineNumber != nil {
		return *m.LineNumber
	}
	return 0
}

// / Request to get a Step Value.
type GetStepValueRequest struct {
	// / The text of the Step.
	StepText *string `protobuf:"bytes,1,req,name=stepText" json:"stepText,omitempty"`
	// / Flag to indicate if the Step has an inline table.
	HasInlineTable   *bool  `protobuf:"varint,2,opt,name=hasInlineTable" json:"hasInlineTable,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetStepValueRequest) Reset()                    { *m = GetStepValueRequest{} }
func (m *GetStepValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStepValueRequest) ProtoMessage()               {}
func (*GetStepValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetStepValueRequest) GetStepText() string {
	if m != nil && m.StepText != nil {
		return *m.StepText
	}
	return ""
}

func (m *GetStepValueRequest) GetHasInlineTable() bool {
	if m != nil && m.HasInlineTable != nil {
		return *m.HasInlineTable
	}
	return false
}

// / Response to GetStepValueRequest
type GetStepValueResponse struct {
	// / The Step corresponding to the request provided.
	StepValue        *ProtoStepValue `protobuf:"bytes,1,req,name=stepValue" json:"stepValue,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GetStepValueResponse) Reset()                    { *m = GetStepValueResponse{} }
func (m *GetStepValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetStepValueResponse) ProtoMessage()               {}
func (*GetStepValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetStepValueResponse) GetStepValue() *ProtoStepValue {
	if m != nil {
		return m.StepValue
	}
	return nil
}

// / Request to get the location of language plugin's Lib directory
type GetLanguagePluginLibPathRequest struct {
	// / The language to locate the lib directory for.
	Language         *string `protobuf:"bytes,1,req,name=language" json:"language,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLanguagePluginLibPathRequest) Reset()         { *m = GetLanguagePluginLibPathRequest{} }
func (m *GetLanguagePluginLibPathRequest) String() string { return proto.CompactTextString(m) }
func (*GetLanguagePluginLibPathRequest) ProtoMessage()    {}
func (*GetLanguagePluginLibPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13}
}

func (m *GetLanguagePluginLibPathRequest) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

// / Response to GetLanguagePluginLibPathRequest
type GetLanguagePluginLibPathResponse struct {
	// / Absolute path to the Lib directory of the language.
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLanguagePluginLibPathResponse) Reset()         { *m = GetLanguagePluginLibPathResponse{} }
func (m *GetLanguagePluginLibPathResponse) String() string { return proto.CompactTextString(m) }
func (*GetLanguagePluginLibPathResponse) ProtoMessage()    {}
func (*GetLanguagePluginLibPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14}
}

func (m *GetLanguagePluginLibPathResponse) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

// / A generic failure response
type ErrorResponse struct {
	// / Actual error message
	Error            *string `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ErrorResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

// / Request to perform a Refactor
type PerformRefactoringRequest struct {
	// / Step to refactor
	OldStep *string `protobuf:"bytes,1,req,name=oldStep" json:"oldStep,omitempty"`
	// / Change to be made
	NewStep          *string `protobuf:"bytes,2,req,name=newStep" json:"newStep,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PerformRefactoringRequest) Reset()                    { *m = PerformRefactoringRequest{} }
func (m *PerformRefactoringRequest) String() string            { return proto.CompactTextString(m) }
func (*PerformRefactoringRequest) ProtoMessage()               {}
func (*PerformRefactoringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PerformRefactoringRequest) GetOldStep() string {
	if m != nil && m.OldStep != nil {
		return *m.OldStep
	}
	return ""
}

func (m *PerformRefactoringRequest) GetNewStep() string {
	if m != nil && m.NewStep != nil {
		return *m.NewStep
	}
	return ""
}

// / Response to PerformRefactoringRequest
type PerformRefactoringResponse struct {
	// / Flag indicating Success
	Success *bool `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	// / Error message if the refactoring was unsuccessful.
	Errors []string `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
	// / Collection of files that were changed as part of the Refactoring.
	FilesChanged     []string `protobuf:"bytes,3,rep,name=filesChanged" json:"filesChanged,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PerformRefactoringResponse) Reset()                    { *m = PerformRefactoringResponse{} }
func (m *PerformRefactoringResponse) String() string            { return proto.CompactTextString(m) }
func (*PerformRefactoringResponse) ProtoMessage()               {}
func (*PerformRefactoringResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PerformRefactoringResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *PerformRefactoringResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *PerformRefactoringResponse) GetFilesChanged() []string {
	if m != nil {
		return m.FilesChanged
	}
	return nil
}

// / Request to perform Extract to Concept refactoring
// / The runner does not do the refactoring here, instead it provides inputs enabling the IDE to do refactoring
type ExtractConceptInfoRequest struct {
	// / The text blob containing steps that should be refactored to concept.
	Text             *string `protobuf:"bytes,1,req,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExtractConceptInfoRequest) Reset()                    { *m = ExtractConceptInfoRequest{} }
func (m *ExtractConceptInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptInfoRequest) ProtoMessage()               {}
func (*ExtractConceptInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ExtractConceptInfoRequest) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

// / Request to perform Extract to Concept refactoring
type ExtractConceptRequest struct {
	// / The Concept name given by the user
	ConceptName *Step `protobuf:"bytes,1,req,name=conceptName" json:"conceptName,omitempty"`
	// / steps to extract
	Steps []*Step `protobuf:"bytes,2,rep,name=steps" json:"steps,omitempty"`
	// / Flag indicating if refactoring should be done across project
	ChangeAcrossProject *bool `protobuf:"varint,3,req,name=changeAcrossProject" json:"changeAcrossProject,omitempty"`
	// / The concept filename in which extracted concept will be added
	ConceptFileName *string `protobuf:"bytes,4,req,name=conceptFileName" json:"conceptFileName,omitempty"`
	// / Info related to selected text, required only if changeAcrossProject is false
	SelectedTextInfo *TextInfo `protobuf:"bytes,5,opt,name=selectedTextInfo" json:"selectedTextInfo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ExtractConceptRequest) Reset()                    { *m = ExtractConceptRequest{} }
func (m *ExtractConceptRequest) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptRequest) ProtoMessage()               {}
func (*ExtractConceptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ExtractConceptRequest) GetConceptName() *Step {
	if m != nil {
		return m.ConceptName
	}
	return nil
}

func (m *ExtractConceptRequest) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *ExtractConceptRequest) GetChangeAcrossProject() bool {
	if m != nil && m.ChangeAcrossProject != nil {
		return *m.ChangeAcrossProject
	}
	return false
}

func (m *ExtractConceptRequest) GetConceptFileName() string {
	if m != nil && m.ConceptFileName != nil {
		return *m.ConceptFileName
	}
	return ""
}

func (m *ExtractConceptRequest) GetSelectedTextInfo() *TextInfo {
	if m != nil {
		return m.SelectedTextInfo
	}
	return nil
}

type TextInfo struct {
	// / The filename from where concept is being extracted
	FileName *string `protobuf:"bytes,1,req,name=fileName" json:"fileName,omitempty"`
	// / storing the starting and ending line number of selected text
	StartingLineNo   *int32 `protobuf:"varint,2,req,name=startingLineNo" json:"startingLineNo,omitempty"`
	EndLineNo        *int32 `protobuf:"varint,3,req,name=endLineNo" json:"endLineNo,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TextInfo) Reset()                    { *m = TextInfo{} }
func (m *TextInfo) String() string            { return proto.CompactTextString(m) }
func (*TextInfo) ProtoMessage()               {}
func (*TextInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *TextInfo) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *TextInfo) GetStartingLineNo() int32 {
	if m != nil && m.StartingLineNo != nil {
		return *m.StartingLineNo
	}
	return 0
}

func (m *TextInfo) GetEndLineNo() int32 {
	if m != nil && m.EndLineNo != nil {
		return *m.EndLineNo
	}
	return 0
}

type Step struct {
	// / name of the step
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// /  table present in step as parameter
	Table *string `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	// / name of table in concept heading, if it comes as a param to concept
	ParamTableName   *string `protobuf:"bytes,3,opt,name=paramTableName" json:"paramTableName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Step) Reset()                    { *m = Step{} }
func (m *Step) String() string            { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()               {}
func (*Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *Step) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Step) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *Step) GetParamTableName() string {
	if m != nil && m.ParamTableName != nil {
		return *m.ParamTableName
	}
	return ""
}

// / Response to perform Extract to Concept refactoring
type ExtractConceptResponse struct {
	// / Flag indicating Success
	IsSuccess *bool `protobuf:"varint,1,req,name=isSuccess" json:"isSuccess,omitempty"`
	// / Error message if the refactoring was unsuccessful.
	Error *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// / Collection of files that were changed as part of the Refactoring.
	FilesChanged     []string `protobuf:"bytes,3,rep,name=filesChanged" json:"filesChanged,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ExtractConceptResponse) Reset()                    { *m = ExtractConceptResponse{} }
func (m *ExtractConceptResponse) String() string            { return proto.CompactTextString(m) }
func (*ExtractConceptResponse) ProtoMessage()               {}
func (*ExtractConceptResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ExtractConceptResponse) GetIsSuccess() bool {
	if m != nil && m.IsSuccess != nil {
		return *m.IsSuccess
	}
	return false
}

func (m *ExtractConceptResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *ExtractConceptResponse) GetFilesChanged() []string {
	if m != nil {
		return m.FilesChanged
	}
	return nil
}

// / Request to format spec files
type FormatSpecsRequest struct {
	// / Specs to be formatted
	Specs            []string `protobuf:"bytes,1,rep,name=specs" json:"specs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FormatSpecsRequest) Reset()                    { *m = FormatSpecsRequest{} }
func (m *FormatSpecsRequest) String() string            { return proto.CompactTextString(m) }
func (*FormatSpecsRequest) ProtoMessage()               {}
func (*FormatSpecsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *FormatSpecsRequest) GetSpecs() []string {
	if m != nil {
		return m.Specs
	}
	return nil
}

// / Response on formatting spec files
type FormatSpecsResponse struct {
	// / Errors occurred on formatting
	Errors []string `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	// / Warnings occurred on formatting
	Warnings         []string `protobuf:"bytes,2,rep,name=warnings" json:"warnings,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FormatSpecsResponse) Reset()                    { *m = FormatSpecsResponse{} }
func (m *FormatSpecsResponse) String() string            { return proto.CompactTextString(m) }
func (*FormatSpecsResponse) ProtoMessage()               {}
func (*FormatSpecsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *FormatSpecsResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *FormatSpecsResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

// / Response when a API message request is not supported.
type UnsupportedApiMessageResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnsupportedApiMessageResponse) Reset()                    { *m = UnsupportedApiMessageResponse{} }
func (m *UnsupportedApiMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsupportedApiMessageResponse) ProtoMessage()               {}
func (*UnsupportedApiMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

// / A generic message composing of all possible operations.
// / One of the Request/Response fields will have value, depending on the MessageType set.
type APIMessage struct {
	// / Type of API call being made
	MessageType *APIMessage_APIMessageType `protobuf:"varint,1,req,name=messageType,enum=gauge.messages.APIMessage_APIMessageType" json:"messageType,omitempty"`
	// / A unique id to represent this message. A response to the message should copy over this value.
	// / This is used to synchronize messages & responses
	MessageId *int64 `protobuf:"varint,2,req,name=messageId" json:"messageId,omitempty"`
	// / [GetProjectRootRequest](#gauge.messages.GetProjectRootRequest)
	ProjectRootRequest *GetProjectRootRequest `protobuf:"bytes,3,opt,name=projectRootRequest" json:"projectRootRequest,omitempty"`
	// / [GetProjectRootResponse](#gauge.messages.GetProjectRootResponse)
	ProjectRootResponse *GetProjectRootResponse `protobuf:"bytes,4,opt,name=projectRootResponse" json:"projectRootResponse,omitempty"`
	// / [GetInstallationRootRequest](#gauge.messages.GetInstallationRootRequest)
	InstallationRootRequest *GetInstallationRootRequest `protobuf:"bytes,5,opt,name=installationRootRequest" json:"installationRootRequest,omitempty"`
	// / [GetInstallationRootResponse](#gauge.messages.GetInstallationRootResponse)
	InstallationRootResponse *GetInstallationRootResponse `protobuf:"bytes,6,opt,name=installationRootResponse" json:"installationRootResponse,omitempty"`
	// / [GetAllStepsRequest](#gauge.messages.GetAllStepsRequest)
	AllStepsRequest *GetAllStepsRequest `protobuf:"bytes,7,opt,name=allStepsRequest" json:"allStepsRequest,omitempty"`
	// / [GetAllStepsResponse](#gauge.messages.GetAllStepsResponse)
	AllStepsResponse *GetAllStepsResponse `protobuf:"bytes,8,opt,name=allStepsResponse" json:"allStepsResponse,omitempty"`
	// / [GetAllSpecsRequest](#gauge.messages.GetAllSpecsRequest)
	AllSpecsRequest *GetAllSpecsRequest `protobuf:"bytes,9,opt,name=allSpecsRequest" json:"allSpecsRequest,omitempty"`
	// / [GetAllSpecsResponse](#gauge.messages.GetAllSpecsResponse)
	AllSpecsResponse *GetAllSpecsResponse `protobuf:"bytes,10,opt,name=allSpecsResponse" json:"allSpecsResponse,omitempty"`
	// / [GetStepValueRequest](#gauge.messages.GetStepValueRequest)
	StepValueRequest *GetStepValueRequest `protobuf:"bytes,11,opt,name=stepValueRequest" json:"stepValueRequest,omitempty"`
	// / [GetStepValueResponse](#gauge.messages.GetStepValueResponse)
	StepValueResponse *GetStepValueResponse `protobuf:"bytes,12,opt,name=stepValueResponse" json:"stepValueResponse,omitempty"`
	// / [GetLanguagePluginLibPathRequest](#gauge.messages.GetLanguagePluginLibPathRequest)
	LibPathRequest *GetLanguagePluginLibPathRequest `protobuf:"bytes,13,opt,name=libPathRequest" json:"libPathRequest,omitempty"`
	// / [GetLanguagePluginLibPathResponse](#gauge.messages.GetLanguagePluginLibPathResponse)
	LibPathResponse *GetLanguagePluginLibPathResponse `protobuf:"bytes,14,opt,name=libPathResponse" json:"libPathResponse,omitempty"`
	// / [ErrorResponse](#gauge.messages.ErrorResponse)
	Error *ErrorResponse `protobuf:"bytes,15,opt,name=error" json:"error,omitempty"`
	// / [GetAllConceptsRequest](#gauge.messages.GetAllConceptsRequest)
	AllConceptsRequest *GetAllConceptsRequest `protobuf:"bytes,16,opt,name=allConceptsRequest" json:"allConceptsRequest,omitempty"`
	// / [GetAllConceptsResponse](#gauge.messages.GetAllConceptsResponse)
	AllConceptsResponse *GetAllConceptsResponse `protobuf:"bytes,17,opt,name=allConceptsResponse" json:"allConceptsResponse,omitempty"`
	// / [PerformRefactoringRequest](#gauge.messages.PerformRefactoringRequest)
	PerformRefactoringRequest *PerformRefactoringRequest `protobuf:"bytes,18,opt,name=performRefactoringRequest" json:"performRefactoringRequest,omitempty"`
	// / [PerformRefactoringResponse](#gauge.messages.PerformRefactoringResponse)
	PerformRefactoringResponse *PerformRefactoringResponse `protobuf:"bytes,19,opt,name=performRefactoringResponse" json:"performRefactoringResponse,omitempty"`
	// / [ExtractConceptRequest](#gauge.messages.ExtractConceptRequest)
	ExtractConceptRequest *ExtractConceptRequest `protobuf:"bytes,20,opt,name=extractConceptRequest" json:"extractConceptRequest,omitempty"`
	// / [ExtractConceptResponse](#gauge.messages.ExtractConceptResponse)
	ExtractConceptResponse *ExtractConceptResponse `protobuf:"bytes,21,opt,name=extractConceptResponse" json:"extractConceptResponse,omitempty"`
	// / [FormatSpecsRequest] (#gauge.messages.FormatSpecsRequest)
	FormatSpecsRequest *FormatSpecsRequest `protobuf:"bytes,22,opt,name=formatSpecsRequest" json:"formatSpecsRequest,omitempty"`
	// / [FormatSpecsResponse] (#gauge.messages.FormatSpecsResponse)
	FormatSpecsResponse *FormatSpecsResponse `protobuf:"bytes,23,opt,name=formatSpecsResponse" json:"formatSpecsResponse,omitempty"`
	// / [UnsupportedApiMessageResponse] (#gauge.messages.UnsupportedApiMessageResponse)
	UnsupportedApiMessageResponse *UnsupportedApiMessageResponse `protobuf:"bytes,24,opt,name=unsupportedApiMessageResponse" json:"unsupportedApiMessageResponse,omitempty"`
	XXX_unrecognized              []byte                         `json:"-"`
}

func (m *APIMessage) Reset()                    { *m = APIMessage{} }
func (m *APIMessage) String() string            { return proto.CompactTextString(m) }
func (*APIMessage) ProtoMessage()               {}
func (*APIMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *APIMessage) GetMessageType() APIMessage_APIMessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return APIMessage_GetProjectRootRequest
}

func (m *APIMessage) GetMessageId() int64 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *APIMessage) GetProjectRootRequest() *GetProjectRootRequest {
	if m != nil {
		return m.ProjectRootRequest
	}
	return nil
}

func (m *APIMessage) GetProjectRootResponse() *GetProjectRootResponse {
	if m != nil {
		return m.ProjectRootResponse
	}
	return nil
}

func (m *APIMessage) GetInstallationRootRequest() *GetInstallationRootRequest {
	if m != nil {
		return m.InstallationRootRequest
	}
	return nil
}

func (m *APIMessage) GetInstallationRootResponse() *GetInstallationRootResponse {
	if m != nil {
		return m.InstallationRootResponse
	}
	return nil
}

func (m *APIMessage) GetAllStepsRequest() *GetAllStepsRequest {
	if m != nil {
		return m.AllStepsRequest
	}
	return nil
}

func (m *APIMessage) GetAllStepsResponse() *GetAllStepsResponse {
	if m != nil {
		return m.AllStepsResponse
	}
	return nil
}

func (m *APIMessage) GetAllSpecsRequest() *GetAllSpecsRequest {
	if m != nil {
		return m.AllSpecsRequest
	}
	return nil
}

func (m *APIMessage) GetAllSpecsResponse() *GetAllSpecsResponse {
	if m != nil {
		return m.AllSpecsResponse
	}
	return nil
}

func (m *APIMessage) GetStepValueRequest() *GetStepValueRequest {
	if m != nil {
		return m.StepValueRequest
	}
	return nil
}

func (m *APIMessage) GetStepValueResponse() *GetStepValueResponse {
	if m != nil {
		return m.StepValueResponse
	}
	return nil
}

func (m *APIMessage) GetLibPathRequest() *GetLanguagePluginLibPathRequest {
	if m != nil {
		return m.LibPathRequest
	}
	return nil
}

func (m *APIMessage) GetLibPathResponse() *GetLanguagePluginLibPathResponse {
	if m != nil {
		return m.LibPathResponse
	}
	return nil
}

func (m *APIMessage) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *APIMessage) GetAllConceptsRequest() *GetAllConceptsRequest {
	if m != nil {
		return m.AllConceptsRequest
	}
	return nil
}

func (m *APIMessage) GetAllConceptsResponse() *GetAllConceptsResponse {
	if m != nil {
		return m.AllConceptsResponse
	}
	return nil
}

func (m *APIMessage) GetPerformRefactoringRequest() *PerformRefactoringRequest {
	if m != nil {
		return m.PerformRefactoringRequest
	}
	return nil
}

func (m *APIMessage) GetPerformRefactoringResponse() *PerformRefactoringResponse {
	if m != nil {
		return m.PerformRefactoringResponse
	}
	return nil
}

func (m *APIMessage) GetExtractConceptRequest() *ExtractConceptRequest {
	if m != nil {
		return m.ExtractConceptRequest
	}
	return nil
}

func (m *APIMessage) GetExtractConceptResponse() *ExtractConceptResponse {
	if m != nil {
		return m.ExtractConceptResponse
	}
	return nil
}

func (m *APIMessage) GetFormatSpecsRequest() *FormatSpecsRequest {
	if m != nil {
		return m.FormatSpecsRequest
	}
	return nil
}

func (m *APIMessage) GetFormatSpecsResponse() *FormatSpecsResponse {
	if m != nil {
		return m.FormatSpecsResponse
	}
	return nil
}

func (m *APIMessage) GetUnsupportedApiMessageResponse() *UnsupportedApiMessageResponse {
	if m != nil {
		return m.UnsupportedApiMessageResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProjectRootRequest)(nil), "gauge.messages.GetProjectRootRequest")
	proto.RegisterType((*GetProjectRootResponse)(nil), "gauge.messages.GetProjectRootResponse")
	proto.RegisterType((*GetInstallationRootRequest)(nil), "gauge.messages.GetInstallationRootRequest")
	proto.RegisterType((*GetInstallationRootResponse)(nil), "gauge.messages.GetInstallationRootResponse")
	proto.RegisterType((*GetAllStepsRequest)(nil), "gauge.messages.GetAllStepsRequest")
	proto.RegisterType((*GetAllStepsResponse)(nil), "gauge.messages.GetAllStepsResponse")
	proto.RegisterType((*GetAllSpecsRequest)(nil), "gauge.messages.GetAllSpecsRequest")
	proto.RegisterType((*GetAllSpecsResponse)(nil), "gauge.messages.GetAllSpecsResponse")
	proto.RegisterType((*GetAllConceptsRequest)(nil), "gauge.messages.GetAllConceptsRequest")
	proto.RegisterType((*GetAllConceptsResponse)(nil), "gauge.messages.GetAllConceptsResponse")
	proto.RegisterType((*ConceptInfo)(nil), "gauge.messages.ConceptInfo")
	proto.RegisterType((*GetStepValueRequest)(nil), "gauge.messages.GetStepValueRequest")
	proto.RegisterType((*GetStepValueResponse)(nil), "gauge.messages.GetStepValueResponse")
	proto.RegisterType((*GetLanguagePluginLibPathRequest)(nil), "gauge.messages.GetLanguagePluginLibPathRequest")
	proto.RegisterType((*GetLanguagePluginLibPathResponse)(nil), "gauge.messages.GetLanguagePluginLibPathResponse")
	proto.RegisterType((*ErrorResponse)(nil), "gauge.messages.ErrorResponse")
	proto.RegisterType((*PerformRefactoringRequest)(nil), "gauge.messages.PerformRefactoringRequest")
	proto.RegisterType((*PerformRefactoringResponse)(nil), "gauge.messages.PerformRefactoringResponse")
	proto.RegisterType((*ExtractConceptInfoRequest)(nil), "gauge.messages.ExtractConceptInfoRequest")
	proto.RegisterType((*ExtractConceptRequest)(nil), "gauge.messages.ExtractConceptRequest")
	proto.RegisterType((*TextInfo)(nil), "gauge.messages.textInfo")
	proto.RegisterType((*Step)(nil), "gauge.messages.step")
	proto.RegisterType((*ExtractConceptResponse)(nil), "gauge.messages.ExtractConceptResponse")
	proto.RegisterType((*FormatSpecsRequest)(nil), "gauge.messages.FormatSpecsRequest")
	proto.RegisterType((*FormatSpecsResponse)(nil), "gauge.messages.FormatSpecsResponse")
	proto.RegisterType((*UnsupportedApiMessageResponse)(nil), "gauge.messages.UnsupportedApiMessageResponse")
	proto.RegisterType((*APIMessage)(nil), "gauge.messages.APIMessage")
	proto.RegisterEnum("gauge.messages.APIMessage_APIMessageType", APIMessage_APIMessageType_name, APIMessage_APIMessageType_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x57, 0x5b, 0x6f, 0xdb, 0xb6,
	0x17, 0x47, 0xe2, 0xb8, 0xb5, 0x8f, 0x1b, 0x87, 0xa1, 0x2f, 0x61, 0xd2, 0xa6, 0xc9, 0x5f, 0xbd,
	0x20, 0xff, 0x0c, 0x4b, 0x8a, 0x0c, 0xe8, 0x80, 0x62, 0x7b, 0x08, 0xba, 0x66, 0x30, 0x96, 0xb5,
	0x1e, 0x9b, 0x6e, 0xdd, 0x06, 0x0c, 0x50, 0x6c, 0xda, 0x51, 0xa1, 0x48, 0x9a, 0x24, 0xa3, 0xdd,
	0x27, 0xd8, 0xa7, 0xd8, 0xe3, 0x3e, 0xe5, 0x5e, 0x46, 0x52, 0x94, 0x25, 0x51, 0x94, 0x12, 0x60,
	0x6f, 0xe2, 0xb9, 0xfc, 0xce, 0xe1, 0xb9, 0xe9, 0x10, 0xda, 0x76, 0xe0, 0x1c, 0x05, 0xa1, 0x1f,
	0xfb, 0xb8, 0x3b, 0xb7, 0x17, 0x73, 0x76, 0x74, 0xcd, 0xa2, 0xc8, 0x9e, 0xb3, 0x68, 0x07, 0xa2,
	0x80, 0x4d, 0x12, 0x9e, 0xb5, 0x05, 0x83, 0x6f, 0x59, 0x3c, 0x0e, 0xfd, 0x0f, 0x6c, 0x12, 0x53,
	0xdf, 0x8f, 0x29, 0xfb, 0x7d, 0xc1, 0xa2, 0xd8, 0x7a, 0x01, 0x43, 0x9d, 0x11, 0x05, 0xbe, 0x17,
	0x31, 0xbc, 0x0f, 0x9d, 0x20, 0x23, 0x93, 0x95, 0xfd, 0xd5, 0x83, 0x36, 0xcd, 0x93, 0xac, 0x07,
	0xb0, 0xc3, 0x75, 0x47, 0x5e, 0x14, 0xdb, 0xae, 0x6b, 0xc7, 0x8e, 0xef, 0xe5, 0x91, 0x47, 0x70,
	0xdf, 0xc8, 0x55, 0xf0, 0x87, 0x80, 0x1c, 0x8d, 0xa7, 0x6c, 0x94, 0xe8, 0x56, 0x1f, 0x30, 0x87,
	0x3a, 0x75, 0xdd, 0xb7, 0x31, 0x0b, 0xa2, 0xd4, 0xc0, 0x0f, 0xd0, 0x2b, 0x50, 0x15, 0xf0, 0x0b,
	0x68, 0xd9, 0x8a, 0xc6, 0x01, 0x1b, 0x07, 0x9d, 0x93, 0x87, 0x47, 0xc5, 0xc8, 0x1c, 0x8d, 0x45,
	0x4c, 0x84, 0xc4, 0x8f, 0xb6, 0xbb, 0x60, 0x74, 0x29, 0x9f, 0x33, 0xc4, 0x43, 0xb7, 0x34, 0x74,
	0xb6, 0x34, 0x94, 0x50, 0x95, 0xa1, 0x63, 0x68, 0x8a, 0x08, 0xa7, 0x56, 0xb6, 0xcd, 0x56, 0xb8,
	0x04, 0x4d, 0xe4, 0x54, 0x12, 0x38, 0xce, 0x4b, 0xdf, 0x9b, 0xb0, 0x20, 0xce, 0xdd, 0x64, 0xa8,
	0x33, 0x94, 0x8d, 0x2f, 0xa1, 0x35, 0x51, 0x34, 0x65, 0xe6, 0xbe, 0x6e, 0x46, 0xe9, 0x8c, 0xbc,
	0x99, 0x4f, 0x97, 0xc2, 0xd6, 0x9f, 0x2b, 0xd0, 0xc9, 0x71, 0xf0, 0x57, 0xd0, 0x8e, 0xd2, 0x0b,
	0xcb, 0x38, 0xdf, 0x1c, 0x96, 0x4c, 0x01, 0xef, 0x40, 0x6b, 0xe6, 0xb8, 0x2c, 0xb0, 0xe3, 0x2b,
	0xb2, 0x2a, 0x93, 0xb4, 0x3c, 0xe3, 0x87, 0x00, 0xae, 0xe3, 0xb1, 0xd7, 0x8b, 0xeb, 0x4b, 0x16,
	0x92, 0x06, 0xe7, 0x36, 0x69, 0x8e, 0x62, 0xfd, 0x2c, 0xa3, 0x97, 0xc1, 0x26, 0x77, 0x16, 0x90,
	0x02, 0xff, 0x82, 0x7d, 0x4a, 0xf3, 0xbe, 0x3c, 0xe3, 0xa7, 0xd0, 0xbd, 0xb2, 0xa3, 0x91, 0x27,
	0x50, 0x2e, 0xec, 0x4b, 0x97, 0x71, 0xa3, 0x2b, 0x07, 0x2d, 0xaa, 0x51, 0xad, 0x0b, 0xe8, 0x17,
	0xa1, 0x55, 0xd4, 0xfe, 0xd3, 0x65, 0xad, 0xaf, 0x61, 0x8f, 0xa3, 0x9e, 0xdb, 0xde, 0x7c, 0xc1,
	0x25, 0xc7, 0xee, 0x62, 0xee, 0x78, 0xe7, 0xce, 0xe5, 0x98, 0x5f, 0x36, 0xe7, 0xbc, 0xab, 0xf8,
	0xa9, 0xf3, 0xe9, 0xd9, 0x7a, 0x0e, 0xfb, 0xd5, 0xea, 0xca, 0x41, 0x0c, 0x6b, 0x32, 0x96, 0x89,
	0xae, 0xfc, 0xb6, 0x9e, 0xc0, 0xfa, 0xab, 0x30, 0xf4, 0xc3, 0xa5, 0x50, 0x1f, 0x9a, 0x4c, 0x10,
	0x94, 0x54, 0x72, 0xb0, 0xde, 0xc0, 0xf6, 0x98, 0x85, 0x33, 0x3f, 0xbc, 0xa6, 0x6c, 0x66, 0x4f,
	0x62, 0x3f, 0x74, 0xbc, 0x79, 0xea, 0x17, 0x81, 0xbb, 0xbe, 0x3b, 0x15, 0xb7, 0x52, 0x4a, 0xe9,
	0x51, 0x70, 0x3c, 0xf6, 0x51, 0x72, 0x92, 0x04, 0xa6, 0x47, 0x2b, 0x84, 0x1d, 0x13, 0xa0, 0x72,
	0x82, 0xeb, 0x45, 0x8b, 0xc9, 0x84, 0x47, 0x4d, 0x22, 0xb6, 0x68, 0x7a, 0xc4, 0x43, 0xb8, 0x23,
	0x3d, 0x8a, 0x38, 0x60, 0x83, 0x03, 0xaa, 0x13, 0xb6, 0xe0, 0x9e, 0xa8, 0x8d, 0xe8, 0xe5, 0x15,
	0x0f, 0x01, 0x9b, 0xf2, 0x8a, 0x10, 0xdc, 0x02, 0xcd, 0x3a, 0x86, 0xed, 0x57, 0x9f, 0xe2, 0x90,
	0x5b, 0xcb, 0x57, 0xaf, 0xba, 0x04, 0x0f, 0x4e, 0x9c, 0x55, 0x85, 0xfc, 0xb6, 0xfe, 0x5a, 0x85,
	0x41, 0x51, 0x23, 0x95, 0x7e, 0x0e, 0x1d, 0x55, 0xf4, 0xaf, 0xed, 0xeb, 0x34, 0xdb, 0x7d, 0x3d,
	0xdb, 0x22, 0xbb, 0x34, 0x2f, 0xc8, 0xe7, 0x4f, 0x33, 0x92, 0x33, 0x62, 0x55, 0xb6, 0x95, 0x59,
	0x23, 0x11, 0xc1, 0xcf, 0xa0, 0x37, 0x91, 0x9e, 0x9f, 0x4e, 0x42, 0x3f, 0x8a, 0xd4, 0xb4, 0x94,
	0xb5, 0xde, 0xa2, 0x26, 0x16, 0x3e, 0x80, 0x0d, 0x65, 0xec, 0x8c, 0xdf, 0x5b, 0x7a, 0xb6, 0x26,
	0xaf, 0xa3, 0x93, 0xf1, 0x37, 0x80, 0x22, 0xe6, 0x72, 0x1d, 0x36, 0x15, 0xb5, 0x2f, 0x02, 0x41,
	0x9a, 0xbc, 0xda, 0x3b, 0x27, 0x44, 0x77, 0x29, 0x56, 0x7c, 0x5a, 0xd2, 0xb0, 0x5c, 0x68, 0xa5,
	0xdc, 0xb4, 0x59, 0x97, 0xe1, 0x50, 0xcd, 0x2a, 0xad, 0xf1, 0xce, 0xe2, 0xb3, 0x35, 0x8c, 0x79,
	0x8a, 0xcf, 0x45, 0x8b, 0xfa, 0xb2, 0x1a, 0x9a, 0x54, 0xa3, 0xe2, 0x07, 0xd0, 0x66, 0xde, 0x54,
	0x89, 0x24, 0x3d, 0x9d, 0x11, 0xac, 0xf7, 0xb0, 0x26, 0x02, 0x23, 0x32, 0xe5, 0x65, 0x56, 0xe4,
	0xb7, 0xa8, 0xda, 0x78, 0xd9, 0xb2, 0xbc, 0x6a, 0xe5, 0x41, 0xd8, 0x0d, 0xec, 0xd0, 0xbe, 0x96,
	0x7d, 0x2b, 0x3d, 0x6b, 0x48, 0xb6, 0x46, 0xb5, 0x02, 0x18, 0xea, 0x69, 0x56, 0x85, 0xc8, 0x3d,
	0x72, 0xa2, 0xb7, 0x85, 0x52, 0xcc, 0x08, 0x59, 0xaf, 0x28, 0xab, 0xf2, 0x70, 0xab, 0x52, 0x3c,
	0x04, 0x7c, 0xc6, 0x6b, 0xdf, 0x8e, 0xf3, 0x23, 0x5f, 0xe0, 0x65, 0xb3, 0xbd, 0x9d, 0x0e, 0xf0,
	0x11, 0xf4, 0x0a, 0xb2, 0xca, 0xb5, 0xac, 0x13, 0x56, 0x0a, 0x9d, 0xc0, 0x13, 0xf1, 0xd1, 0x0e,
	0x3d, 0x1e, 0xd5, 0xb4, 0x47, 0x96, 0x67, 0x6b, 0x0f, 0x76, 0xdf, 0x79, 0xd1, 0x22, 0x08, 0xfc,
	0x90, 0xe7, 0xf1, 0x34, 0x70, 0xbe, 0x4f, 0xb2, 0x9c, 0x82, 0x5a, 0x7f, 0x0f, 0x00, 0x4e, 0xc7,
	0x23, 0x45, 0xc6, 0xdf, 0x41, 0x47, 0xd5, 0xc1, 0xc5, 0x1f, 0x41, 0x12, 0xf1, 0xee, 0xc9, 0xff,
	0xf5, 0x0a, 0xc9, 0x14, 0x72, 0x9f, 0x42, 0x81, 0xe6, 0xb5, 0x45, 0x2c, 0xd5, 0x71, 0x34, 0x95,
	0x05, 0xd0, 0xa0, 0x19, 0x01, 0xbf, 0x03, 0x1c, 0x94, 0x16, 0x05, 0x99, 0xaf, 0xce, 0xc9, 0x13,
	0xdd, 0xa2, 0x71, 0xab, 0xa0, 0x06, 0x00, 0xfc, 0x1e, 0x7a, 0x41, 0x79, 0xcd, 0xe0, 0x6d, 0x21,
	0x70, 0x9f, 0xde, 0x84, 0x9b, 0x48, 0x53, 0x13, 0x04, 0x9e, 0xc2, 0x96, 0x63, 0x5e, 0x42, 0x54,
	0x27, 0x1d, 0x1a, 0xd0, 0x2b, 0xd6, 0x16, 0x5a, 0x05, 0x85, 0xe7, 0x40, 0x9c, 0x8a, 0x65, 0x86,
	0xdc, 0x91, 0x66, 0x3e, 0xbb, 0x95, 0x19, 0x75, 0x93, 0x4a, 0x30, 0x7c, 0x0e, 0x1b, 0x76, 0x71,
	0xd5, 0x21, 0x77, 0x25, 0xbe, 0x65, 0xc0, 0xd7, 0x96, 0x22, 0xaa, 0xab, 0xe2, 0x37, 0x80, 0x6c,
	0x6d, 0x45, 0x22, 0x2d, 0x09, 0xf7, 0xa8, 0x16, 0x4e, 0xb9, 0x59, 0x52, 0x4e, 0xdd, 0xcb, 0x75,
	0x0b, 0x69, 0xd7, 0xba, 0x97, 0x93, 0xa4, 0xba, 0x6a, 0xea, 0x5e, 0xbe, 0x9f, 0x08, 0xd4, 0xba,
	0x97, 0x17, 0xa5, 0x25, 0x65, 0x01, 0x18, 0x69, 0xbb, 0x06, 0xe9, 0x54, 0x02, 0xea, 0x6b, 0x09,
	0x2d, 0x29, 0x63, 0x0a, 0x9b, 0x91, 0xbe, 0x61, 0x90, 0x7b, 0x12, 0xf1, 0x71, 0x3d, 0xa2, 0xf2,
	0xb1, 0xac, 0x8e, 0x7f, 0x82, 0xae, 0x5b, 0xd8, 0x28, 0xc8, 0xba, 0x04, 0x3c, 0x36, 0x00, 0xd6,
	0x2d, 0x22, 0x54, 0x83, 0xc1, 0xbf, 0xc0, 0x86, 0x5b, 0xdc, 0x35, 0x48, 0x57, 0x22, 0x3f, 0xbb,
	0x3d, 0xb2, 0x72, 0x5b, 0x07, 0xc2, 0x5f, 0xa4, 0x33, 0x76, 0x43, 0x22, 0xee, 0xea, 0x88, 0x85,
	0xed, 0x25, 0x1d, 0xc1, 0x7c, 0x98, 0xd8, 0xa5, 0x85, 0x97, 0xa0, 0xca, 0x61, 0x52, 0xde, 0x8e,
	0xa9, 0x01, 0x40, 0x0c, 0x13, 0xbb, 0xbc, 0x2e, 0x93, 0xcd, 0xca, 0x61, 0x62, 0x58, 0xae, 0xa9,
	0x09, 0x82, 0xb7, 0xf9, 0x76, 0x50, 0xb5, 0x5f, 0x11, 0x2c, 0xf1, 0x4b, 0x63, 0xb7, 0x72, 0x21,
	0xa3, 0xd5, 0x58, 0xf8, 0x03, 0xec, 0x04, 0x95, 0x7b, 0x17, 0xe9, 0x99, 0x07, 0x57, 0xf5, 0xa6,
	0x46, 0x6b, 0xd0, 0xf0, 0xaf, 0x30, 0x60, 0xa6, 0xed, 0x89, 0xf4, 0xcd, 0x89, 0x30, 0xae, 0x5a,
	0xd4, 0x8c, 0x81, 0x7f, 0x83, 0x21, 0x33, 0xfe, 0xb3, 0xc9, 0xc0, 0x9c, 0x0e, 0xf3, 0x1f, 0x9e,
	0x56, 0xa0, 0xf0, 0x06, 0xc4, 0xb3, 0xd2, 0x1f, 0x9a, 0x0c, 0xcd, 0x33, 0xa7, 0xfc, 0x2f, 0xa7,
	0x06, 0x6d, 0x5e, 0x96, 0xbd, 0x59, 0xf9, 0x4f, 0x4e, 0xb6, 0xcc, 0x83, 0xc2, 0xf0, 0xd3, 0xa7,
	0x26, 0x7d, 0x1c, 0xc1, 0xee, 0xa2, 0xee, 0xaf, 0x4e, 0x88, 0x34, 0xf0, 0xb9, 0x6e, 0xa0, 0x76,
	0x15, 0xa0, 0xf5, 0x98, 0xd6, 0x3f, 0x6b, 0xd0, 0x2d, 0xfe, 0xed, 0xf1, 0x76, 0xc5, 0x73, 0x1f,
	0xad, 0xf0, 0xa5, 0xa4, 0xe2, 0xc1, 0x8f, 0x56, 0xf9, 0x53, 0xae, 0xe6, 0x41, 0x8f, 0x1a, 0x78,
	0xaf, 0xf6, 0x49, 0x8f, 0xd6, 0xf8, 0x26, 0x64, 0x78, 0xa8, 0xa3, 0x66, 0x91, 0xbe, 0x94, 0xbf,
	0x93, 0xa3, 0xe7, 0x92, 0x83, 0xee, 0xe2, 0x2d, 0xe3, 0x8b, 0x1b, 0xb5, 0x14, 0x43, 0x9f, 0xda,
	0xa8, 0xcd, 0xdf, 0x29, 0xc6, 0xa7, 0x20, 0x02, 0xfc, 0xe8, 0xc6, 0xe7, 0x1c, 0xea, 0xe0, 0xc7,
	0x37, 0x3f, 0xda, 0xd0, 0x3d, 0xbc, 0xa9, 0x3d, 0xd1, 0xd0, 0xba, 0x8a, 0x74, 0x79, 0x6a, 0xa1,
	0xae, 0x8a, 0xb4, 0x61, 0xf0, 0xa0, 0x0d, 0xbc, 0x5b, 0xf3, 0x8a, 0x43, 0x48, 0x24, 0xa2, 0xba,
	0xd3, 0xd1, 0xa6, 0xb0, 0x6a, 0x6c, 0x51, 0x84, 0x85, 0x55, 0x73, 0x7f, 0xa1, 0x9e, 0x08, 0x77,
	0xb9, 0x3f, 0x50, 0x5f, 0x44, 0xd5, 0x50, 0xe2, 0x68, 0x80, 0xff, 0x77, 0xc3, 0x96, 0x8a, 0x86,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x64, 0x56, 0x7a, 0x81, 0x12, 0x00, 0x00,
}
