// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package gauge_messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StepValidateResponse_ErrorType int32

const (
	StepValidateResponse_STEP_IMPLEMENTATION_NOT_FOUND StepValidateResponse_ErrorType = 0
	StepValidateResponse_DUPLICATE_STEP_IMPLEMENTATION StepValidateResponse_ErrorType = 1
)

var StepValidateResponse_ErrorType_name = map[int32]string{
	0: "STEP_IMPLEMENTATION_NOT_FOUND",
	1: "DUPLICATE_STEP_IMPLEMENTATION",
}
var StepValidateResponse_ErrorType_value = map[string]int32{
	"STEP_IMPLEMENTATION_NOT_FOUND": 0,
	"DUPLICATE_STEP_IMPLEMENTATION": 1,
}

func (x StepValidateResponse_ErrorType) String() string {
	return proto.EnumName(StepValidateResponse_ErrorType_name, int32(x))
}
func (StepValidateResponse_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{16, 0}
}

type CacheFileRequest_FileStatus int32

const (
	// / The file content was changed in the client
	CacheFileRequest_CHANGED CacheFileRequest_FileStatus = 0
	// / The file was closed in the client
	CacheFileRequest_CLOSED CacheFileRequest_FileStatus = 1
	// / The file was created on the client
	CacheFileRequest_CREATED CacheFileRequest_FileStatus = 2
	// / The file was deleted on the client
	CacheFileRequest_DELETED CacheFileRequest_FileStatus = 3
	// / The file is opened in the client
	CacheFileRequest_OPENED CacheFileRequest_FileStatus = 4
)

var CacheFileRequest_FileStatus_name = map[int32]string{
	0: "CHANGED",
	1: "CLOSED",
	2: "CREATED",
	3: "DELETED",
	4: "OPENED",
}
var CacheFileRequest_FileStatus_value = map[string]int32{
	"CHANGED": 0,
	"CLOSED":  1,
	"CREATED": 2,
	"DELETED": 3,
	"OPENED":  4,
}

func (x CacheFileRequest_FileStatus) String() string {
	return proto.EnumName(CacheFileRequest_FileStatus_name, int32(x))
}
func (CacheFileRequest_FileStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor2, []int{30, 0}
}

type Message_MessageType int32

const (
	Message_ExecutionStarting                     Message_MessageType = 0
	Message_SpecExecutionStarting                 Message_MessageType = 1
	Message_SpecExecutionEnding                   Message_MessageType = 2
	Message_ScenarioExecutionStarting             Message_MessageType = 3
	Message_ScenarioExecutionEnding               Message_MessageType = 4
	Message_StepExecutionStarting                 Message_MessageType = 5
	Message_StepExecutionEnding                   Message_MessageType = 6
	Message_ExecuteStep                           Message_MessageType = 7
	Message_ExecutionEnding                       Message_MessageType = 8
	Message_StepValidateRequest                   Message_MessageType = 9
	Message_StepValidateResponse                  Message_MessageType = 10
	Message_ExecutionStatusResponse               Message_MessageType = 11
	Message_StepNamesRequest                      Message_MessageType = 12
	Message_StepNamesResponse                     Message_MessageType = 13
	Message_KillProcessRequest                    Message_MessageType = 14
	Message_SuiteExecutionResult                  Message_MessageType = 15
	Message_ScenarioDataStoreInit                 Message_MessageType = 16
	Message_SpecDataStoreInit                     Message_MessageType = 17
	Message_SuiteDataStoreInit                    Message_MessageType = 18
	Message_StepNameRequest                       Message_MessageType = 19
	Message_StepNameResponse                      Message_MessageType = 20
	Message_RefactorRequest                       Message_MessageType = 21
	Message_RefactorResponse                      Message_MessageType = 22
	Message_UnsupportedMessageResponse            Message_MessageType = 23
	Message_CacheFileRequest                      Message_MessageType = 24
	Message_StepPositionsRequest                  Message_MessageType = 25
	Message_StepPositionsResponse                 Message_MessageType = 26
	Message_ImplementationFileListRequest         Message_MessageType = 27
	Message_ImplementationFileListResponse        Message_MessageType = 28
	Message_StubImplementationCodeRequest         Message_MessageType = 29
	Message_FileDiff                              Message_MessageType = 30
	Message_ImplementationFileGlobPatternRequest  Message_MessageType = 31
	Message_ImplementationFileGlobPatternResponse Message_MessageType = 32
)

var Message_MessageType_name = map[int32]string{
	0:  "ExecutionStarting",
	1:  "SpecExecutionStarting",
	2:  "SpecExecutionEnding",
	3:  "ScenarioExecutionStarting",
	4:  "ScenarioExecutionEnding",
	5:  "StepExecutionStarting",
	6:  "StepExecutionEnding",
	7:  "ExecuteStep",
	8:  "ExecutionEnding",
	9:  "StepValidateRequest",
	10: "StepValidateResponse",
	11: "ExecutionStatusResponse",
	12: "StepNamesRequest",
	13: "StepNamesResponse",
	14: "KillProcessRequest",
	15: "SuiteExecutionResult",
	16: "ScenarioDataStoreInit",
	17: "SpecDataStoreInit",
	18: "SuiteDataStoreInit",
	19: "StepNameRequest",
	20: "StepNameResponse",
	21: "RefactorRequest",
	22: "RefactorResponse",
	23: "UnsupportedMessageResponse",
	24: "CacheFileRequest",
	25: "StepPositionsRequest",
	26: "StepPositionsResponse",
	27: "ImplementationFileListRequest",
	28: "ImplementationFileListResponse",
	29: "StubImplementationCodeRequest",
	30: "FileDiff",
	31: "ImplementationFileGlobPatternRequest",
	32: "ImplementationFileGlobPatternResponse",
}
var Message_MessageType_value = map[string]int32{
	"ExecutionStarting":                     0,
	"SpecExecutionStarting":                 1,
	"SpecExecutionEnding":                   2,
	"ScenarioExecutionStarting":             3,
	"ScenarioExecutionEnding":               4,
	"StepExecutionStarting":                 5,
	"StepExecutionEnding":                   6,
	"ExecuteStep":                           7,
	"ExecutionEnding":                       8,
	"StepValidateRequest":                   9,
	"StepValidateResponse":                  10,
	"ExecutionStatusResponse":               11,
	"StepNamesRequest":                      12,
	"StepNamesResponse":                     13,
	"KillProcessRequest":                    14,
	"SuiteExecutionResult":                  15,
	"ScenarioDataStoreInit":                 16,
	"SpecDataStoreInit":                     17,
	"SuiteDataStoreInit":                    18,
	"StepNameRequest":                       19,
	"StepNameResponse":                      20,
	"RefactorRequest":                       21,
	"RefactorResponse":                      22,
	"UnsupportedMessageResponse":            23,
	"CacheFileRequest":                      24,
	"StepPositionsRequest":                  25,
	"StepPositionsResponse":                 26,
	"ImplementationFileListRequest":         27,
	"ImplementationFileListResponse":        28,
	"StubImplementationCodeRequest":         29,
	"FileDiff":                              30,
	"ImplementationFileGlobPatternRequest":  31,
	"ImplementationFileGlobPatternResponse": 32,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (Message_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{40, 0} }

// / Default request. Tells the runner to shutdown.
type KillProcessRequest struct {
}

func (m *KillProcessRequest) Reset()                    { *m = KillProcessRequest{} }
func (m *KillProcessRequest) String() string            { return proto.CompactTextString(m) }
func (*KillProcessRequest) ProtoMessage()               {}
func (*KillProcessRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// / Sends to any request which needs a execution status as response
// / usually step execution, hooks etc will return this
type ExecutionStatusResponse struct {
	ExecutionResult *ProtoExecutionResult `protobuf:"bytes,1,opt,name=executionResult" json:"executionResult,omitempty"`
}

func (m *ExecutionStatusResponse) Reset()                    { *m = ExecutionStatusResponse{} }
func (m *ExecutionStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecutionStatusResponse) ProtoMessage()               {}
func (*ExecutionStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ExecutionStatusResponse) GetExecutionResult() *ProtoExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

// / Sent at start of Suite Execution. Tells the runner to execute `before_suite` hook.
type ExecutionStartingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *ExecutionStartingRequest) Reset()                    { *m = ExecutionStartingRequest{} }
func (m *ExecutionStartingRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecutionStartingRequest) ProtoMessage()               {}
func (*ExecutionStartingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ExecutionStartingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at end of Suite Execution. Tells the runner to execute `after_suite` hook.
type ExecutionEndingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *ExecutionEndingRequest) Reset()                    { *m = ExecutionEndingRequest{} }
func (m *ExecutionEndingRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecutionEndingRequest) ProtoMessage()               {}
func (*ExecutionEndingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ExecutionEndingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at start of Spec Execution. Tells the runner to execute `before_spec` hook.
type SpecExecutionStartingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *SpecExecutionStartingRequest) Reset()                    { *m = SpecExecutionStartingRequest{} }
func (m *SpecExecutionStartingRequest) String() string            { return proto.CompactTextString(m) }
func (*SpecExecutionStartingRequest) ProtoMessage()               {}
func (*SpecExecutionStartingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *SpecExecutionStartingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at end of Spec Execution. Tells the runner to execute `after_spec` hook.
type SpecExecutionEndingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *SpecExecutionEndingRequest) Reset()                    { *m = SpecExecutionEndingRequest{} }
func (m *SpecExecutionEndingRequest) String() string            { return proto.CompactTextString(m) }
func (*SpecExecutionEndingRequest) ProtoMessage()               {}
func (*SpecExecutionEndingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *SpecExecutionEndingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at start of Scenario Execution. Tells the runner to execute `before_scenario` hook.
type ScenarioExecutionStartingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *ScenarioExecutionStartingRequest) Reset()         { *m = ScenarioExecutionStartingRequest{} }
func (m *ScenarioExecutionStartingRequest) String() string { return proto.CompactTextString(m) }
func (*ScenarioExecutionStartingRequest) ProtoMessage()    {}
func (*ScenarioExecutionStartingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{6}
}

func (m *ScenarioExecutionStartingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at end of Scenario Execution. Tells the runner to execute `after_scenario` hook.
type ScenarioExecutionEndingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *ScenarioExecutionEndingRequest) Reset()                    { *m = ScenarioExecutionEndingRequest{} }
func (m *ScenarioExecutionEndingRequest) String() string            { return proto.CompactTextString(m) }
func (*ScenarioExecutionEndingRequest) ProtoMessage()               {}
func (*ScenarioExecutionEndingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *ScenarioExecutionEndingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at start of Step Execution. Tells the runner to execute `before_step` hook.
type StepExecutionStartingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *StepExecutionStartingRequest) Reset()                    { *m = StepExecutionStartingRequest{} }
func (m *StepExecutionStartingRequest) String() string            { return proto.CompactTextString(m) }
func (*StepExecutionStartingRequest) ProtoMessage()               {}
func (*StepExecutionStartingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *StepExecutionStartingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Sent at end of Step Execution. Tells the runner to execute `after_step` hook.
type StepExecutionEndingRequest struct {
	CurrentExecutionInfo *ExecutionInfo `protobuf:"bytes,1,opt,name=currentExecutionInfo" json:"currentExecutionInfo,omitempty"`
}

func (m *StepExecutionEndingRequest) Reset()                    { *m = StepExecutionEndingRequest{} }
func (m *StepExecutionEndingRequest) String() string            { return proto.CompactTextString(m) }
func (*StepExecutionEndingRequest) ProtoMessage()               {}
func (*StepExecutionEndingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *StepExecutionEndingRequest) GetCurrentExecutionInfo() *ExecutionInfo {
	if m != nil {
		return m.CurrentExecutionInfo
	}
	return nil
}

// / Contains details of the execution.
// / Depending on the context (Step, Scenario, Spec or Suite), the respective fields are set.
type ExecutionInfo struct {
	// / Holds the information of the current Spec. Valid in context of Spec execution.
	CurrentSpec *SpecInfo `protobuf:"bytes,1,opt,name=currentSpec" json:"currentSpec,omitempty"`
	// / Holds the information of the current Scenario. Valid in context of Scenario execution.
	CurrentScenario *ScenarioInfo `protobuf:"bytes,2,opt,name=currentScenario" json:"currentScenario,omitempty"`
	// / Holds the information of the current Step. Valid in context of Step execution.
	CurrentStep *StepInfo `protobuf:"bytes,3,opt,name=currentStep" json:"currentStep,omitempty"`
	// / Stacktrace of the execution. Valid only if there is an error in execution.
	Stacktrace string `protobuf:"bytes,4,opt,name=stacktrace" json:"stacktrace,omitempty"`
}

func (m *ExecutionInfo) Reset()                    { *m = ExecutionInfo{} }
func (m *ExecutionInfo) String() string            { return proto.CompactTextString(m) }
func (*ExecutionInfo) ProtoMessage()               {}
func (*ExecutionInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *ExecutionInfo) GetCurrentSpec() *SpecInfo {
	if m != nil {
		return m.CurrentSpec
	}
	return nil
}

func (m *ExecutionInfo) GetCurrentScenario() *ScenarioInfo {
	if m != nil {
		return m.CurrentScenario
	}
	return nil
}

func (m *ExecutionInfo) GetCurrentStep() *StepInfo {
	if m != nil {
		return m.CurrentStep
	}
	return nil
}

func (m *ExecutionInfo) GetStacktrace() string {
	if m != nil {
		return m.Stacktrace
	}
	return ""
}

// / Contains details of the Spec execution.
type SpecInfo struct {
	// / Name of the current Spec being executed.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// / Full File path containing the current Spec being executed.
	FileName string `protobuf:"bytes,2,opt,name=fileName" json:"fileName,omitempty"`
	// / Flag to indicate if the current Spec execution failed.
	IsFailed bool `protobuf:"varint,3,opt,name=isFailed" json:"isFailed,omitempty"`
	// / Tags relevant to the current Spec execution.
	Tags []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *SpecInfo) Reset()                    { *m = SpecInfo{} }
func (m *SpecInfo) String() string            { return proto.CompactTextString(m) }
func (*SpecInfo) ProtoMessage()               {}
func (*SpecInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *SpecInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpecInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *SpecInfo) GetIsFailed() bool {
	if m != nil {
		return m.IsFailed
	}
	return false
}

func (m *SpecInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// / Contains details of the Scenario execution.
type ScenarioInfo struct {
	// / Name of the current Scenario being executed.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// / Flag to indicate if the current Scenario execution failed.
	IsFailed bool `protobuf:"varint,2,opt,name=isFailed" json:"isFailed,omitempty"`
	// / Tags relevant to the current Scenario execution.
	Tags []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *ScenarioInfo) Reset()                    { *m = ScenarioInfo{} }
func (m *ScenarioInfo) String() string            { return proto.CompactTextString(m) }
func (*ScenarioInfo) ProtoMessage()               {}
func (*ScenarioInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *ScenarioInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScenarioInfo) GetIsFailed() bool {
	if m != nil {
		return m.IsFailed
	}
	return false
}

func (m *ScenarioInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// / Contains details of the Step execution.
type StepInfo struct {
	// / The current request to execute Step
	Step *ExecuteStepRequest `protobuf:"bytes,1,opt,name=step" json:"step,omitempty"`
	// / Flag to indicate if the current Step execution failed.
	IsFailed bool `protobuf:"varint,2,opt,name=isFailed" json:"isFailed,omitempty"`
	// / The current stack trace in case of failure
	StackTrace string `protobuf:"bytes,3,opt,name=stackTrace" json:"stackTrace,omitempty"`
	// / The error message in case of failure
	ErrorMessage string `protobuf:"bytes,4,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *StepInfo) Reset()                    { *m = StepInfo{} }
func (m *StepInfo) String() string            { return proto.CompactTextString(m) }
func (*StepInfo) ProtoMessage()               {}
func (*StepInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *StepInfo) GetStep() *ExecuteStepRequest {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *StepInfo) GetIsFailed() bool {
	if m != nil {
		return m.IsFailed
	}
	return false
}

func (m *StepInfo) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *StepInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// / Request sent ot the runner to Execute a Step
type ExecuteStepRequest struct {
	// / Contains the actual text of the Step being executed.
	// / This contains the parameters as defined in the Spec.
	ActualStepText string `protobuf:"bytes,1,opt,name=actualStepText" json:"actualStepText,omitempty"`
	// / Contains the parsed text of the Step being executed.
	// / The paramters are replaced with placeholders.
	ParsedStepText string `protobuf:"bytes,2,opt,name=parsedStepText" json:"parsedStepText,omitempty"`
	// / Flag to indicate if the execution of the Scenario, containing the current Step, failed.
	ScenarioFailing bool `protobuf:"varint,3,opt,name=scenarioFailing" json:"scenarioFailing,omitempty"`
	// / Collection of parameters applicable to the current Step.
	Parameters []*Parameter `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty"`
}

func (m *ExecuteStepRequest) Reset()                    { *m = ExecuteStepRequest{} }
func (m *ExecuteStepRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteStepRequest) ProtoMessage()               {}
func (*ExecuteStepRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *ExecuteStepRequest) GetActualStepText() string {
	if m != nil {
		return m.ActualStepText
	}
	return ""
}

func (m *ExecuteStepRequest) GetParsedStepText() string {
	if m != nil {
		return m.ParsedStepText
	}
	return ""
}

func (m *ExecuteStepRequest) GetScenarioFailing() bool {
	if m != nil {
		return m.ScenarioFailing
	}
	return false
}

func (m *ExecuteStepRequest) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// / Request sent ot the runner to check if given Step is valid.
// / The runner should check if there is an implementation defined for the given Step Text.
type StepValidateRequest struct {
	// / The text is used to lookup Step implementation
	StepText string `protobuf:"bytes,1,opt,name=stepText" json:"stepText,omitempty"`
	// / The number of paramters in the Step
	NumberOfParameters int32 `protobuf:"varint,2,opt,name=numberOfParameters" json:"numberOfParameters,omitempty"`
	// /This is use to generate step implementation template
	StepValue *ProtoStepValue `protobuf:"bytes,3,opt,name=stepValue" json:"stepValue,omitempty"`
}

func (m *StepValidateRequest) Reset()                    { *m = StepValidateRequest{} }
func (m *StepValidateRequest) String() string            { return proto.CompactTextString(m) }
func (*StepValidateRequest) ProtoMessage()               {}
func (*StepValidateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *StepValidateRequest) GetStepText() string {
	if m != nil {
		return m.StepText
	}
	return ""
}

func (m *StepValidateRequest) GetNumberOfParameters() int32 {
	if m != nil {
		return m.NumberOfParameters
	}
	return 0
}

func (m *StepValidateRequest) GetStepValue() *ProtoStepValue {
	if m != nil {
		return m.StepValue
	}
	return nil
}

// / Response of StepValidateRequest.
// / The runner tells the caller if the Request was valid,
// / i.e. an implementation exists for given Step text.
// / Returns an error message if it is an error response.
type StepValidateResponse struct {
	IsValid      bool                           `protobuf:"varint,1,opt,name=isValid" json:"isValid,omitempty"`
	ErrorMessage string                         `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
	ErrorType    StepValidateResponse_ErrorType `protobuf:"varint,3,opt,name=errorType,enum=gauge.messages.StepValidateResponse_ErrorType" json:"errorType,omitempty"`
	Suggestion   string                         `protobuf:"bytes,4,opt,name=suggestion" json:"suggestion,omitempty"`
}

func (m *StepValidateResponse) Reset()                    { *m = StepValidateResponse{} }
func (m *StepValidateResponse) String() string            { return proto.CompactTextString(m) }
func (*StepValidateResponse) ProtoMessage()               {}
func (*StepValidateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *StepValidateResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *StepValidateResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *StepValidateResponse) GetErrorType() StepValidateResponse_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return StepValidateResponse_STEP_IMPLEMENTATION_NOT_FOUND
}

func (m *StepValidateResponse) GetSuggestion() string {
	if m != nil {
		return m.Suggestion
	}
	return ""
}

// / Result of the Suite Execution.
type SuiteExecutionResult struct {
	SuiteResult *ProtoSuiteResult `protobuf:"bytes,1,opt,name=suiteResult" json:"suiteResult,omitempty"`
}

func (m *SuiteExecutionResult) Reset()                    { *m = SuiteExecutionResult{} }
func (m *SuiteExecutionResult) String() string            { return proto.CompactTextString(m) }
func (*SuiteExecutionResult) ProtoMessage()               {}
func (*SuiteExecutionResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *SuiteExecutionResult) GetSuiteResult() *ProtoSuiteResult {
	if m != nil {
		return m.SuiteResult
	}
	return nil
}

// / Requests Gauge to give all Step Names.
type StepNamesRequest struct {
}

func (m *StepNamesRequest) Reset()                    { *m = StepNamesRequest{} }
func (m *StepNamesRequest) String() string            { return proto.CompactTextString(m) }
func (*StepNamesRequest) ProtoMessage()               {}
func (*StepNamesRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

// / Response to StepNamesRequest
type StepNamesResponse struct {
	// / Collection of strings corresponding to Step texts.
	Steps []string `protobuf:"bytes,1,rep,name=steps" json:"steps,omitempty"`
}

func (m *StepNamesResponse) Reset()                    { *m = StepNamesResponse{} }
func (m *StepNamesResponse) String() string            { return proto.CompactTextString(m) }
func (*StepNamesResponse) ProtoMessage()               {}
func (*StepNamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *StepNamesResponse) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

// / Request runner to initialize Scenario DataStore
// / Scenario Datastore is reset after every Scenario execution.
type ScenarioDataStoreInitRequest struct {
}

func (m *ScenarioDataStoreInitRequest) Reset()                    { *m = ScenarioDataStoreInitRequest{} }
func (m *ScenarioDataStoreInitRequest) String() string            { return proto.CompactTextString(m) }
func (*ScenarioDataStoreInitRequest) ProtoMessage()               {}
func (*ScenarioDataStoreInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{20} }

// / Request runner to initialize Spec DataStore
// / Spec Datastore is reset after every Spec execution.
type SpecDataStoreInitRequest struct {
}

func (m *SpecDataStoreInitRequest) Reset()                    { *m = SpecDataStoreInitRequest{} }
func (m *SpecDataStoreInitRequest) String() string            { return proto.CompactTextString(m) }
func (*SpecDataStoreInitRequest) ProtoMessage()               {}
func (*SpecDataStoreInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{21} }

// / Request runner to initialize Suite DataStore
// / Suite Datastore is reset after every Suite execution.
type SuiteDataStoreInitRequest struct {
}

func (m *SuiteDataStoreInitRequest) Reset()                    { *m = SuiteDataStoreInitRequest{} }
func (m *SuiteDataStoreInitRequest) String() string            { return proto.CompactTextString(m) }
func (*SuiteDataStoreInitRequest) ProtoMessage()               {}
func (*SuiteDataStoreInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{22} }

// / Holds the new and old positions of a parameter.
// / Used when refactoring a Step.
type ParameterPosition struct {
	OldPosition int32 `protobuf:"varint,1,opt,name=oldPosition" json:"oldPosition,omitempty"`
	NewPosition int32 `protobuf:"varint,2,opt,name=newPosition" json:"newPosition,omitempty"`
}

func (m *ParameterPosition) Reset()                    { *m = ParameterPosition{} }
func (m *ParameterPosition) String() string            { return proto.CompactTextString(m) }
func (*ParameterPosition) ProtoMessage()               {}
func (*ParameterPosition) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{23} }

func (m *ParameterPosition) GetOldPosition() int32 {
	if m != nil {
		return m.OldPosition
	}
	return 0
}

func (m *ParameterPosition) GetNewPosition() int32 {
	if m != nil {
		return m.NewPosition
	}
	return 0
}

// / Tells the runner to refactor the specified Step.
type RefactorRequest struct {
	// / Old value, used to lookup Step to refactor
	OldStepValue *ProtoStepValue `protobuf:"bytes,1,opt,name=oldStepValue" json:"oldStepValue,omitempty"`
	// / New value, the to-be value of Step being refactored.
	NewStepValue *ProtoStepValue `protobuf:"bytes,2,opt,name=newStepValue" json:"newStepValue,omitempty"`
	// / Holds parameter positions of all parameters. Contains old and new parameter positions.
	ParamPositions []*ParameterPosition `protobuf:"bytes,3,rep,name=paramPositions" json:"paramPositions,omitempty"`
	// / If set to true, the refactored files should be saved to the file system before returning the response.
	SaveChanges bool `protobuf:"varint,4,opt,name=saveChanges" json:"saveChanges,omitempty"`
}

func (m *RefactorRequest) Reset()                    { *m = RefactorRequest{} }
func (m *RefactorRequest) String() string            { return proto.CompactTextString(m) }
func (*RefactorRequest) ProtoMessage()               {}
func (*RefactorRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{24} }

func (m *RefactorRequest) GetOldStepValue() *ProtoStepValue {
	if m != nil {
		return m.OldStepValue
	}
	return nil
}

func (m *RefactorRequest) GetNewStepValue() *ProtoStepValue {
	if m != nil {
		return m.NewStepValue
	}
	return nil
}

func (m *RefactorRequest) GetParamPositions() []*ParameterPosition {
	if m != nil {
		return m.ParamPositions
	}
	return nil
}

func (m *RefactorRequest) GetSaveChanges() bool {
	if m != nil {
		return m.SaveChanges
	}
	return false
}

// / Give all file changes to be made to file system
type FileChanges struct {
	FileName    string `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	FileContent string `protobuf:"bytes,2,opt,name=fileContent" json:"fileContent,omitempty"`
}

func (m *FileChanges) Reset()                    { *m = FileChanges{} }
func (m *FileChanges) String() string            { return proto.CompactTextString(m) }
func (*FileChanges) ProtoMessage()               {}
func (*FileChanges) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{25} }

func (m *FileChanges) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileChanges) GetFileContent() string {
	if m != nil {
		return m.FileContent
	}
	return ""
}

// / Response of a RefactorRequest
type RefactorResponse struct {
	// / Flag indicating the success of Refactor operation.
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	// / Error message, valid only if Refactor wasn't successful
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// / List of files that were affected because of the refactoring.
	FilesChanged []string `protobuf:"bytes,3,rep,name=filesChanged" json:"filesChanged,omitempty"`
	// / List of file changes to be made to successfully achieve refactoring.
	FileChanges []*FileChanges `protobuf:"bytes,4,rep,name=fileChanges" json:"fileChanges,omitempty"`
}

func (m *RefactorResponse) Reset()                    { *m = RefactorResponse{} }
func (m *RefactorResponse) String() string            { return proto.CompactTextString(m) }
func (*RefactorResponse) ProtoMessage()               {}
func (*RefactorResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{26} }

func (m *RefactorResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RefactorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RefactorResponse) GetFilesChanged() []string {
	if m != nil {
		return m.FilesChanged
	}
	return nil
}

func (m *RefactorResponse) GetFileChanges() []*FileChanges {
	if m != nil {
		return m.FileChanges
	}
	return nil
}

// / Request for details on a Single Step.
type StepNameRequest struct {
	// / Step text to lookup the Step.
	// / This is the parsed step value, i.e. with placeholders for parameters.
	StepValue string `protobuf:"bytes,1,opt,name=stepValue" json:"stepValue,omitempty"`
}

func (m *StepNameRequest) Reset()                    { *m = StepNameRequest{} }
func (m *StepNameRequest) String() string            { return proto.CompactTextString(m) }
func (*StepNameRequest) ProtoMessage()               {}
func (*StepNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{27} }

func (m *StepNameRequest) GetStepValue() string {
	if m != nil {
		return m.StepValue
	}
	return ""
}

// / Response to StepNameRequest.
type StepNameResponse struct {
	// / Flag indicating if there is a match for the given Step Text.
	IsStepPresent bool `protobuf:"varint,1,opt,name=isStepPresent" json:"isStepPresent,omitempty"`
	// / The Step name of the given step.
	StepName []string `protobuf:"bytes,2,rep,name=stepName" json:"stepName,omitempty"`
	// / Flag indicating if the given Step is an alias.
	HasAlias bool `protobuf:"varint,3,opt,name=hasAlias" json:"hasAlias,omitempty"`
	// / File name in which the step implementation exists
	FileName string `protobuf:"bytes,4,opt,name=fileName" json:"fileName,omitempty"`
	// / Range of step
	Span *Span `protobuf:"bytes,5,opt,name=span" json:"span,omitempty"`
}

func (m *StepNameResponse) Reset()                    { *m = StepNameResponse{} }
func (m *StepNameResponse) String() string            { return proto.CompactTextString(m) }
func (*StepNameResponse) ProtoMessage()               {}
func (*StepNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{28} }

func (m *StepNameResponse) GetIsStepPresent() bool {
	if m != nil {
		return m.IsStepPresent
	}
	return false
}

func (m *StepNameResponse) GetStepName() []string {
	if m != nil {
		return m.StepName
	}
	return nil
}

func (m *StepNameResponse) GetHasAlias() bool {
	if m != nil {
		return m.HasAlias
	}
	return false
}

func (m *StepNameResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *StepNameResponse) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

// / Response when a unsupported message request is sent.
type UnsupportedMessageResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UnsupportedMessageResponse) Reset()                    { *m = UnsupportedMessageResponse{} }
func (m *UnsupportedMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*UnsupportedMessageResponse) ProtoMessage()               {}
func (*UnsupportedMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{29} }

func (m *UnsupportedMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// / Request for caching a file.
// / Gauge sends this request when running in LSP mode,
// / so runner can cache file contents present on the client(an editor).
type CacheFileRequest struct {
	// / File content of the file to be cached
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	// / File path of the file to be cached
	FilePath string `protobuf:"bytes,2,opt,name=filePath" json:"filePath,omitempty"`
	// / Specifies if the file is closed
	IsClosed bool `protobuf:"varint,3,opt,name=isClosed" json:"isClosed,omitempty"`
	// / Specifies the status of the file
	Status CacheFileRequest_FileStatus `protobuf:"varint,4,opt,name=status,enum=gauge.messages.CacheFileRequest_FileStatus" json:"status,omitempty"`
}

func (m *CacheFileRequest) Reset()                    { *m = CacheFileRequest{} }
func (m *CacheFileRequest) String() string            { return proto.CompactTextString(m) }
func (*CacheFileRequest) ProtoMessage()               {}
func (*CacheFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{30} }

func (m *CacheFileRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CacheFileRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *CacheFileRequest) GetIsClosed() bool {
	if m != nil {
		return m.IsClosed
	}
	return false
}

func (m *CacheFileRequest) GetStatus() CacheFileRequest_FileStatus {
	if m != nil {
		return m.Status
	}
	return CacheFileRequest_CHANGED
}

// / Request for find step positions
type StepPositionsRequest struct {
	// / Get step positions for file path
	FilePath string `protobuf:"bytes,1,opt,name=filePath" json:"filePath,omitempty"`
}

func (m *StepPositionsRequest) Reset()                    { *m = StepPositionsRequest{} }
func (m *StepPositionsRequest) String() string            { return proto.CompactTextString(m) }
func (*StepPositionsRequest) ProtoMessage()               {}
func (*StepPositionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{31} }

func (m *StepPositionsRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

// / Response for find step positions
type StepPositionsResponse struct {
	// / Step Position
	StepPositions []*StepPositionsResponse_StepPosition `protobuf:"bytes,1,rep,name=stepPositions" json:"stepPositions,omitempty"`
	// / Error message
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *StepPositionsResponse) Reset()                    { *m = StepPositionsResponse{} }
func (m *StepPositionsResponse) String() string            { return proto.CompactTextString(m) }
func (*StepPositionsResponse) ProtoMessage()               {}
func (*StepPositionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{32} }

func (m *StepPositionsResponse) GetStepPositions() []*StepPositionsResponse_StepPosition {
	if m != nil {
		return m.StepPositions
	}
	return nil
}

func (m *StepPositionsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// / Step position for each step implementation
type StepPositionsResponse_StepPosition struct {
	// / Step Value
	StepValue string `protobuf:"bytes,1,opt,name=stepValue" json:"stepValue,omitempty"`
	// / Range of step
	Span *Span `protobuf:"bytes,2,opt,name=span" json:"span,omitempty"`
}

func (m *StepPositionsResponse_StepPosition) Reset()         { *m = StepPositionsResponse_StepPosition{} }
func (m *StepPositionsResponse_StepPosition) String() string { return proto.CompactTextString(m) }
func (*StepPositionsResponse_StepPosition) ProtoMessage()    {}
func (*StepPositionsResponse_StepPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{32, 0}
}

func (m *StepPositionsResponse_StepPosition) GetStepValue() string {
	if m != nil {
		return m.StepValue
	}
	return ""
}

func (m *StepPositionsResponse_StepPosition) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

// / Request for getting Implementation file glob pattern
type ImplementationFileGlobPatternRequest struct {
}

func (m *ImplementationFileGlobPatternRequest) Reset()         { *m = ImplementationFileGlobPatternRequest{} }
func (m *ImplementationFileGlobPatternRequest) String() string { return proto.CompactTextString(m) }
func (*ImplementationFileGlobPatternRequest) ProtoMessage()    {}
func (*ImplementationFileGlobPatternRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{33}
}

// / Response for getting Implementation file glob pattern
type ImplementationFileGlobPatternResponse struct {
	// / List of implementation file glob patterns
	GlobPatterns []string `protobuf:"bytes,1,rep,name=globPatterns" json:"globPatterns,omitempty"`
}

func (m *ImplementationFileGlobPatternResponse) Reset()         { *m = ImplementationFileGlobPatternResponse{} }
func (m *ImplementationFileGlobPatternResponse) String() string { return proto.CompactTextString(m) }
func (*ImplementationFileGlobPatternResponse) ProtoMessage()    {}
func (*ImplementationFileGlobPatternResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{34}
}

func (m *ImplementationFileGlobPatternResponse) GetGlobPatterns() []string {
	if m != nil {
		return m.GlobPatterns
	}
	return nil
}

// / Request for getting Implementation file list
type ImplementationFileListRequest struct {
}

func (m *ImplementationFileListRequest) Reset()                    { *m = ImplementationFileListRequest{} }
func (m *ImplementationFileListRequest) String() string            { return proto.CompactTextString(m) }
func (*ImplementationFileListRequest) ProtoMessage()               {}
func (*ImplementationFileListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{35} }

// / Response for getting Implementation file list
type ImplementationFileListResponse struct {
	// / List of implementation files
	ImplementationFilePaths []string `protobuf:"bytes,1,rep,name=implementationFilePaths" json:"implementationFilePaths,omitempty"`
}

func (m *ImplementationFileListResponse) Reset()                    { *m = ImplementationFileListResponse{} }
func (m *ImplementationFileListResponse) String() string            { return proto.CompactTextString(m) }
func (*ImplementationFileListResponse) ProtoMessage()               {}
func (*ImplementationFileListResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{36} }

func (m *ImplementationFileListResponse) GetImplementationFilePaths() []string {
	if m != nil {
		return m.ImplementationFilePaths
	}
	return nil
}

// / Request for injecting code snippet into implementation file
type StubImplementationCodeRequest struct {
	// / Path of the file where the new stub implementation will be added
	ImplementationFilePath string `protobuf:"bytes,1,opt,name=implementationFilePath" json:"implementationFilePath,omitempty"`
	// / List of implementation codes to be appended to implementation file.
	Codes []string `protobuf:"bytes,2,rep,name=codes" json:"codes,omitempty"`
}

func (m *StubImplementationCodeRequest) Reset()                    { *m = StubImplementationCodeRequest{} }
func (m *StubImplementationCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*StubImplementationCodeRequest) ProtoMessage()               {}
func (*StubImplementationCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{37} }

func (m *StubImplementationCodeRequest) GetImplementationFilePath() string {
	if m != nil {
		return m.ImplementationFilePath
	}
	return ""
}

func (m *StubImplementationCodeRequest) GetCodes() []string {
	if m != nil {
		return m.Codes
	}
	return nil
}

// / A Single Replace Diff Element to be applied
type TextDiff struct {
	// / Range of file to be replaced
	Span *Span `protobuf:"bytes,1,opt,name=span" json:"span,omitempty"`
	// / New content to replace the content in the span
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *TextDiff) Reset()                    { *m = TextDiff{} }
func (m *TextDiff) String() string            { return proto.CompactTextString(m) }
func (*TextDiff) ProtoMessage()               {}
func (*TextDiff) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{38} }

func (m *TextDiff) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *TextDiff) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// / Diffs to be applied to a file
type FileDiff struct {
	// / File Path where the new content needs to be put in
	FilePath string `protobuf:"bytes,1,opt,name=filePath" json:"filePath,omitempty"`
	// / The diffs which need to be applied to this file
	TextDiffs []*TextDiff `protobuf:"bytes,2,rep,name=textDiffs" json:"textDiffs,omitempty"`
}

func (m *FileDiff) Reset()                    { *m = FileDiff{} }
func (m *FileDiff) String() string            { return proto.CompactTextString(m) }
func (*FileDiff) ProtoMessage()               {}
func (*FileDiff) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{39} }

func (m *FileDiff) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *FileDiff) GetTextDiffs() []*TextDiff {
	if m != nil {
		return m.TextDiffs
	}
	return nil
}

// / This is the message which gets transferred all the time
// / with proper message type set
// / One of the Request/Response fields will have value, depending on the MessageType set.
type Message struct {
	MessageType Message_MessageType `protobuf:"varint,1,opt,name=messageType,enum=gauge.messages.Message_MessageType" json:"messageType,omitempty"`
	// / A unique id to represent this message. A response to the message should copy over this value.
	// / This is used to synchronize messages & responses
	MessageId int64 `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
	// / [ExecutionStartingRequest](#gauge.messages.ExecutionStartingRequest)
	ExecutionStartingRequest *ExecutionStartingRequest `protobuf:"bytes,3,opt,name=executionStartingRequest" json:"executionStartingRequest,omitempty"`
	// / [SpecExecutionStartingRequest](#gauge.messages.SpecExecutionStartingRequest)
	SpecExecutionStartingRequest *SpecExecutionStartingRequest `protobuf:"bytes,4,opt,name=specExecutionStartingRequest" json:"specExecutionStartingRequest,omitempty"`
	// / [SpecExecutionEndingRequest](#gauge.messages.SpecExecutionEndingRequest)
	SpecExecutionEndingRequest *SpecExecutionEndingRequest `protobuf:"bytes,5,opt,name=specExecutionEndingRequest" json:"specExecutionEndingRequest,omitempty"`
	// / [ScenarioExecutionStartingRequest](#gauge.messages.ScenarioExecutionStartingRequest)
	ScenarioExecutionStartingRequest *ScenarioExecutionStartingRequest `protobuf:"bytes,6,opt,name=scenarioExecutionStartingRequest" json:"scenarioExecutionStartingRequest,omitempty"`
	// / [ScenarioExecutionEndingRequest](#gauge.messages.ScenarioExecutionEndingRequest)
	ScenarioExecutionEndingRequest *ScenarioExecutionEndingRequest `protobuf:"bytes,7,opt,name=scenarioExecutionEndingRequest" json:"scenarioExecutionEndingRequest,omitempty"`
	// / [StepExecutionStartingRequest](#gauge.messages.StepExecutionStartingRequest)
	StepExecutionStartingRequest *StepExecutionStartingRequest `protobuf:"bytes,8,opt,name=stepExecutionStartingRequest" json:"stepExecutionStartingRequest,omitempty"`
	// / [StepExecutionEndingRequest](#gauge.messages.StepExecutionEndingRequest)
	StepExecutionEndingRequest *StepExecutionEndingRequest `protobuf:"bytes,9,opt,name=stepExecutionEndingRequest" json:"stepExecutionEndingRequest,omitempty"`
	// / [ExecuteStepRequest](#gauge.messages.ExecuteStepRequest)
	ExecuteStepRequest *ExecuteStepRequest `protobuf:"bytes,10,opt,name=executeStepRequest" json:"executeStepRequest,omitempty"`
	// / [ExecutionEndingRequest](#gauge.messages.ExecutionEndingRequest)
	ExecutionEndingRequest *ExecutionEndingRequest `protobuf:"bytes,11,opt,name=executionEndingRequest" json:"executionEndingRequest,omitempty"`
	// / [StepValidateRequest](#gauge.messages.StepValidateRequest)
	StepValidateRequest *StepValidateRequest `protobuf:"bytes,12,opt,name=stepValidateRequest" json:"stepValidateRequest,omitempty"`
	// / [StepValidateResponse](#gauge.messages.StepValidateResponse)
	StepValidateResponse *StepValidateResponse `protobuf:"bytes,13,opt,name=stepValidateResponse" json:"stepValidateResponse,omitempty"`
	// / [ExecutionStatusResponse](#gauge.messages.ExecutionStatusResponse)
	ExecutionStatusResponse *ExecutionStatusResponse `protobuf:"bytes,14,opt,name=executionStatusResponse" json:"executionStatusResponse,omitempty"`
	// / [StepNamesRequest](#gauge.messages.StepNamesRequest)
	StepNamesRequest *StepNamesRequest `protobuf:"bytes,15,opt,name=stepNamesRequest" json:"stepNamesRequest,omitempty"`
	// / [StepNamesResponse](#gauge.messages.StepNamesResponse)
	StepNamesResponse *StepNamesResponse `protobuf:"bytes,16,opt,name=stepNamesResponse" json:"stepNamesResponse,omitempty"`
	// / [SuiteExecutionResult ](#gauge.messages.SuiteExecutionResult )
	SuiteExecutionResult *SuiteExecutionResult `protobuf:"bytes,17,opt,name=suiteExecutionResult" json:"suiteExecutionResult,omitempty"`
	// / [KillProcessRequest](#gauge.messages.KillProcessRequest)
	KillProcessRequest *KillProcessRequest `protobuf:"bytes,18,opt,name=killProcessRequest" json:"killProcessRequest,omitempty"`
	// / [ScenarioDataStoreInitRequest](#gauge.messages.ScenarioDataStoreInitRequest)
	ScenarioDataStoreInitRequest *ScenarioDataStoreInitRequest `protobuf:"bytes,19,opt,name=scenarioDataStoreInitRequest" json:"scenarioDataStoreInitRequest,omitempty"`
	// / [SpecDataStoreInitRequest](#gauge.messages.SpecDataStoreInitRequest)
	SpecDataStoreInitRequest *SpecDataStoreInitRequest `protobuf:"bytes,20,opt,name=specDataStoreInitRequest" json:"specDataStoreInitRequest,omitempty"`
	// / [SuiteDataStoreInitRequest](#gauge.messages.SuiteDataStoreInitRequest)
	SuiteDataStoreInitRequest *SuiteDataStoreInitRequest `protobuf:"bytes,21,opt,name=suiteDataStoreInitRequest" json:"suiteDataStoreInitRequest,omitempty"`
	// / [StepNameRequest](#gauge.messages.StepNameRequest)
	StepNameRequest *StepNameRequest `protobuf:"bytes,22,opt,name=stepNameRequest" json:"stepNameRequest,omitempty"`
	// / [StepNameResponse](#gauge.messages.StepNameResponse)
	StepNameResponse *StepNameResponse `protobuf:"bytes,23,opt,name=stepNameResponse" json:"stepNameResponse,omitempty"`
	// / [RefactorRequest](#gauge.messages.RefactorRequest)
	RefactorRequest *RefactorRequest `protobuf:"bytes,24,opt,name=refactorRequest" json:"refactorRequest,omitempty"`
	// / [RefactorResponse](#gauge.messages.RefactorResponse)
	RefactorResponse *RefactorResponse `protobuf:"bytes,25,opt,name=refactorResponse" json:"refactorResponse,omitempty"`
	// / [UnsupportedMessageResponse](#gauge.messages.UnsupportedMessageResponse)
	UnsupportedMessageResponse *UnsupportedMessageResponse `protobuf:"bytes,26,opt,name=unsupportedMessageResponse" json:"unsupportedMessageResponse,omitempty"`
	// / [CacheFileRequest](#gauge.messages.CacheFileRequest)
	CacheFileRequest *CacheFileRequest `protobuf:"bytes,27,opt,name=cacheFileRequest" json:"cacheFileRequest,omitempty"`
	// / [StepPositionsRequest](#gauge.messages.StepPositionsRequest)
	StepPositionsRequest *StepPositionsRequest `protobuf:"bytes,28,opt,name=stepPositionsRequest" json:"stepPositionsRequest,omitempty"`
	// / [StepPositionsResponse](#gauge.messages.StepPositionsResponse)
	StepPositionsResponse *StepPositionsResponse `protobuf:"bytes,29,opt,name=stepPositionsResponse" json:"stepPositionsResponse,omitempty"`
	// / [ImplementationFileListRequest](#gauge.messages.ImplementationFileListRequest)
	ImplementationFileListRequest *ImplementationFileListRequest `protobuf:"bytes,30,opt,name=implementationFileListRequest" json:"implementationFileListRequest,omitempty"`
	// / [ImplementationFileListResponse](#gauge.messages.ImplementationFileListResponse)
	ImplementationFileListResponse *ImplementationFileListResponse `protobuf:"bytes,31,opt,name=implementationFileListResponse" json:"implementationFileListResponse,omitempty"`
	// / [StubImplementationCodeRequest](#gauge.messages.StubImplementationCodeRequest)
	StubImplementationCodeRequest *StubImplementationCodeRequest `protobuf:"bytes,32,opt,name=stubImplementationCodeRequest" json:"stubImplementationCodeRequest,omitempty"`
	// / [FileDiff](#gauge.messages.FileDiff)
	FileDiff *FileDiff `protobuf:"bytes,33,opt,name=fileDiff" json:"fileDiff,omitempty"`
	// / [ImplementationFileGlobPatternRequest](#gauge.messages.ImplementationFileGlobPatternRequest)
	ImplementationFileGlobPatternRequest *ImplementationFileGlobPatternRequest `protobuf:"bytes,34,opt,name=implementationFileGlobPatternRequest" json:"implementationFileGlobPatternRequest,omitempty"`
	// / [ImplementationFileGlobPatternResponse](#gauge.messages.ImplementationFileGlobPatternResponse)
	ImplementationFileGlobPatternResponse *ImplementationFileGlobPatternResponse `protobuf:"bytes,35,opt,name=implementationFileGlobPatternResponse" json:"implementationFileGlobPatternResponse,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{40} }

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_ExecutionStarting
}

func (m *Message) GetMessageId() int64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Message) GetExecutionStartingRequest() *ExecutionStartingRequest {
	if m != nil {
		return m.ExecutionStartingRequest
	}
	return nil
}

func (m *Message) GetSpecExecutionStartingRequest() *SpecExecutionStartingRequest {
	if m != nil {
		return m.SpecExecutionStartingRequest
	}
	return nil
}

func (m *Message) GetSpecExecutionEndingRequest() *SpecExecutionEndingRequest {
	if m != nil {
		return m.SpecExecutionEndingRequest
	}
	return nil
}

func (m *Message) GetScenarioExecutionStartingRequest() *ScenarioExecutionStartingRequest {
	if m != nil {
		return m.ScenarioExecutionStartingRequest
	}
	return nil
}

func (m *Message) GetScenarioExecutionEndingRequest() *ScenarioExecutionEndingRequest {
	if m != nil {
		return m.ScenarioExecutionEndingRequest
	}
	return nil
}

func (m *Message) GetStepExecutionStartingRequest() *StepExecutionStartingRequest {
	if m != nil {
		return m.StepExecutionStartingRequest
	}
	return nil
}

func (m *Message) GetStepExecutionEndingRequest() *StepExecutionEndingRequest {
	if m != nil {
		return m.StepExecutionEndingRequest
	}
	return nil
}

func (m *Message) GetExecuteStepRequest() *ExecuteStepRequest {
	if m != nil {
		return m.ExecuteStepRequest
	}
	return nil
}

func (m *Message) GetExecutionEndingRequest() *ExecutionEndingRequest {
	if m != nil {
		return m.ExecutionEndingRequest
	}
	return nil
}

func (m *Message) GetStepValidateRequest() *StepValidateRequest {
	if m != nil {
		return m.StepValidateRequest
	}
	return nil
}

func (m *Message) GetStepValidateResponse() *StepValidateResponse {
	if m != nil {
		return m.StepValidateResponse
	}
	return nil
}

func (m *Message) GetExecutionStatusResponse() *ExecutionStatusResponse {
	if m != nil {
		return m.ExecutionStatusResponse
	}
	return nil
}

func (m *Message) GetStepNamesRequest() *StepNamesRequest {
	if m != nil {
		return m.StepNamesRequest
	}
	return nil
}

func (m *Message) GetStepNamesResponse() *StepNamesResponse {
	if m != nil {
		return m.StepNamesResponse
	}
	return nil
}

func (m *Message) GetSuiteExecutionResult() *SuiteExecutionResult {
	if m != nil {
		return m.SuiteExecutionResult
	}
	return nil
}

func (m *Message) GetKillProcessRequest() *KillProcessRequest {
	if m != nil {
		return m.KillProcessRequest
	}
	return nil
}

func (m *Message) GetScenarioDataStoreInitRequest() *ScenarioDataStoreInitRequest {
	if m != nil {
		return m.ScenarioDataStoreInitRequest
	}
	return nil
}

func (m *Message) GetSpecDataStoreInitRequest() *SpecDataStoreInitRequest {
	if m != nil {
		return m.SpecDataStoreInitRequest
	}
	return nil
}

func (m *Message) GetSuiteDataStoreInitRequest() *SuiteDataStoreInitRequest {
	if m != nil {
		return m.SuiteDataStoreInitRequest
	}
	return nil
}

func (m *Message) GetStepNameRequest() *StepNameRequest {
	if m != nil {
		return m.StepNameRequest
	}
	return nil
}

func (m *Message) GetStepNameResponse() *StepNameResponse {
	if m != nil {
		return m.StepNameResponse
	}
	return nil
}

func (m *Message) GetRefactorRequest() *RefactorRequest {
	if m != nil {
		return m.RefactorRequest
	}
	return nil
}

func (m *Message) GetRefactorResponse() *RefactorResponse {
	if m != nil {
		return m.RefactorResponse
	}
	return nil
}

func (m *Message) GetUnsupportedMessageResponse() *UnsupportedMessageResponse {
	if m != nil {
		return m.UnsupportedMessageResponse
	}
	return nil
}

func (m *Message) GetCacheFileRequest() *CacheFileRequest {
	if m != nil {
		return m.CacheFileRequest
	}
	return nil
}

func (m *Message) GetStepPositionsRequest() *StepPositionsRequest {
	if m != nil {
		return m.StepPositionsRequest
	}
	return nil
}

func (m *Message) GetStepPositionsResponse() *StepPositionsResponse {
	if m != nil {
		return m.StepPositionsResponse
	}
	return nil
}

func (m *Message) GetImplementationFileListRequest() *ImplementationFileListRequest {
	if m != nil {
		return m.ImplementationFileListRequest
	}
	return nil
}

func (m *Message) GetImplementationFileListResponse() *ImplementationFileListResponse {
	if m != nil {
		return m.ImplementationFileListResponse
	}
	return nil
}

func (m *Message) GetStubImplementationCodeRequest() *StubImplementationCodeRequest {
	if m != nil {
		return m.StubImplementationCodeRequest
	}
	return nil
}

func (m *Message) GetFileDiff() *FileDiff {
	if m != nil {
		return m.FileDiff
	}
	return nil
}

func (m *Message) GetImplementationFileGlobPatternRequest() *ImplementationFileGlobPatternRequest {
	if m != nil {
		return m.ImplementationFileGlobPatternRequest
	}
	return nil
}

func (m *Message) GetImplementationFileGlobPatternResponse() *ImplementationFileGlobPatternResponse {
	if m != nil {
		return m.ImplementationFileGlobPatternResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*KillProcessRequest)(nil), "gauge.messages.KillProcessRequest")
	proto.RegisterType((*ExecutionStatusResponse)(nil), "gauge.messages.ExecutionStatusResponse")
	proto.RegisterType((*ExecutionStartingRequest)(nil), "gauge.messages.ExecutionStartingRequest")
	proto.RegisterType((*ExecutionEndingRequest)(nil), "gauge.messages.ExecutionEndingRequest")
	proto.RegisterType((*SpecExecutionStartingRequest)(nil), "gauge.messages.SpecExecutionStartingRequest")
	proto.RegisterType((*SpecExecutionEndingRequest)(nil), "gauge.messages.SpecExecutionEndingRequest")
	proto.RegisterType((*ScenarioExecutionStartingRequest)(nil), "gauge.messages.ScenarioExecutionStartingRequest")
	proto.RegisterType((*ScenarioExecutionEndingRequest)(nil), "gauge.messages.ScenarioExecutionEndingRequest")
	proto.RegisterType((*StepExecutionStartingRequest)(nil), "gauge.messages.StepExecutionStartingRequest")
	proto.RegisterType((*StepExecutionEndingRequest)(nil), "gauge.messages.StepExecutionEndingRequest")
	proto.RegisterType((*ExecutionInfo)(nil), "gauge.messages.ExecutionInfo")
	proto.RegisterType((*SpecInfo)(nil), "gauge.messages.SpecInfo")
	proto.RegisterType((*ScenarioInfo)(nil), "gauge.messages.ScenarioInfo")
	proto.RegisterType((*StepInfo)(nil), "gauge.messages.StepInfo")
	proto.RegisterType((*ExecuteStepRequest)(nil), "gauge.messages.ExecuteStepRequest")
	proto.RegisterType((*StepValidateRequest)(nil), "gauge.messages.StepValidateRequest")
	proto.RegisterType((*StepValidateResponse)(nil), "gauge.messages.StepValidateResponse")
	proto.RegisterType((*SuiteExecutionResult)(nil), "gauge.messages.SuiteExecutionResult")
	proto.RegisterType((*StepNamesRequest)(nil), "gauge.messages.StepNamesRequest")
	proto.RegisterType((*StepNamesResponse)(nil), "gauge.messages.StepNamesResponse")
	proto.RegisterType((*ScenarioDataStoreInitRequest)(nil), "gauge.messages.ScenarioDataStoreInitRequest")
	proto.RegisterType((*SpecDataStoreInitRequest)(nil), "gauge.messages.SpecDataStoreInitRequest")
	proto.RegisterType((*SuiteDataStoreInitRequest)(nil), "gauge.messages.SuiteDataStoreInitRequest")
	proto.RegisterType((*ParameterPosition)(nil), "gauge.messages.ParameterPosition")
	proto.RegisterType((*RefactorRequest)(nil), "gauge.messages.RefactorRequest")
	proto.RegisterType((*FileChanges)(nil), "gauge.messages.FileChanges")
	proto.RegisterType((*RefactorResponse)(nil), "gauge.messages.RefactorResponse")
	proto.RegisterType((*StepNameRequest)(nil), "gauge.messages.StepNameRequest")
	proto.RegisterType((*StepNameResponse)(nil), "gauge.messages.StepNameResponse")
	proto.RegisterType((*UnsupportedMessageResponse)(nil), "gauge.messages.UnsupportedMessageResponse")
	proto.RegisterType((*CacheFileRequest)(nil), "gauge.messages.CacheFileRequest")
	proto.RegisterType((*StepPositionsRequest)(nil), "gauge.messages.StepPositionsRequest")
	proto.RegisterType((*StepPositionsResponse)(nil), "gauge.messages.StepPositionsResponse")
	proto.RegisterType((*StepPositionsResponse_StepPosition)(nil), "gauge.messages.StepPositionsResponse.StepPosition")
	proto.RegisterType((*ImplementationFileGlobPatternRequest)(nil), "gauge.messages.ImplementationFileGlobPatternRequest")
	proto.RegisterType((*ImplementationFileGlobPatternResponse)(nil), "gauge.messages.ImplementationFileGlobPatternResponse")
	proto.RegisterType((*ImplementationFileListRequest)(nil), "gauge.messages.ImplementationFileListRequest")
	proto.RegisterType((*ImplementationFileListResponse)(nil), "gauge.messages.ImplementationFileListResponse")
	proto.RegisterType((*StubImplementationCodeRequest)(nil), "gauge.messages.StubImplementationCodeRequest")
	proto.RegisterType((*TextDiff)(nil), "gauge.messages.TextDiff")
	proto.RegisterType((*FileDiff)(nil), "gauge.messages.FileDiff")
	proto.RegisterType((*Message)(nil), "gauge.messages.Message")
	proto.RegisterEnum("gauge.messages.StepValidateResponse_ErrorType", StepValidateResponse_ErrorType_name, StepValidateResponse_ErrorType_value)
	proto.RegisterEnum("gauge.messages.CacheFileRequest_FileStatus", CacheFileRequest_FileStatus_name, CacheFileRequest_FileStatus_value)
	proto.RegisterEnum("gauge.messages.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 2212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x5a, 0x4f, 0x6f, 0x1b, 0xb9,
	0x15, 0xdf, 0x91, 0x1d, 0x5b, 0x7e, 0x72, 0x2c, 0x9a, 0x96, 0x6d, 0x5a, 0xb1, 0x1d, 0x79, 0xf2,
	0xa7, 0x4e, 0xff, 0xb8, 0x85, 0xbb, 0x0d, 0xda, 0xa2, 0x3d, 0x24, 0xb6, 0x92, 0x1a, 0x71, 0x6c,
	0x2d, 0xed, 0x6c, 0x17, 0x5b, 0x60, 0x83, 0x89, 0x44, 0x2b, 0xb3, 0x91, 0x67, 0xb4, 0xc3, 0xd1,
	0xee, 0x16, 0xe8, 0xb9, 0x28, 0xd0, 0x73, 0xcf, 0x05, 0x0a, 0x14, 0x28, 0xfa, 0x01, 0xfa, 0x1d,
	0xfa, 0x29, 0xfa, 0x11, 0x7a, 0x6a, 0xcf, 0x05, 0x39, 0xe4, 0x68, 0x86, 0xc3, 0x19, 0xb9, 0x87,
	0xe4, 0x14, 0xf1, 0xcd, 0x7b, 0xbf, 0xf7, 0x8f, 0x7c, 0x7c, 0x8f, 0x31, 0xac, 0x5c, 0x33, 0xce,
	0xbd, 0x21, 0xe3, 0x07, 0xe3, 0x28, 0x8c, 0x43, 0xbc, 0x32, 0xf4, 0x26, 0x43, 0x76, 0xa0, 0xa9,
	0x6d, 0xe0, 0x63, 0xd6, 0x4f, 0xbe, 0xb9, 0x2d, 0xc0, 0x2f, 0xfc, 0xd1, 0xa8, 0x17, 0x85, 0x7d,
	0xc6, 0x39, 0x65, 0x5f, 0x4d, 0x18, 0x8f, 0x5d, 0x1f, 0x36, 0xbb, 0xdf, 0xb2, 0xfe, 0x24, 0xf6,
	0xc3, 0xe0, 0x22, 0xf6, 0xe2, 0x09, 0xa7, 0x8c, 0x8f, 0xc3, 0x80, 0x33, 0x7c, 0x06, 0x4d, 0xa6,
	0x3f, 0x51, 0xc6, 0x27, 0xa3, 0x98, 0x38, 0x1d, 0x67, 0xbf, 0x71, 0x78, 0xff, 0x20, 0xaf, 0xe6,
	0xa0, 0x27, 0x14, 0x74, 0xf3, 0xbc, 0xd4, 0x14, 0x76, 0xaf, 0x81, 0x64, 0x55, 0x45, 0xb1, 0x1f,
	0x0c, 0x95, 0x19, 0xf8, 0x13, 0x68, 0xf5, 0x27, 0x51, 0xc4, 0x82, 0x38, 0x65, 0x39, 0x09, 0xae,
	0x42, 0xa5, 0x70, 0xc7, 0x54, 0x98, 0x63, 0xa2, 0x56, 0x51, 0xf7, 0x1d, 0x6c, 0xa4, 0x84, 0x6e,
	0x30, 0x78, 0xbf, 0xca, 0xbe, 0x82, 0xed, 0x8b, 0x31, 0xeb, 0x7f, 0x48, 0xff, 0x42, 0x68, 0xe7,
	0x54, 0xbe, 0x77, 0x1f, 0x27, 0xd0, 0xb9, 0xe8, 0xb3, 0xc0, 0x8b, 0xfc, 0xf0, 0x43, 0xfa, 0xc9,
	0x61, 0xb7, 0xa0, 0xf6, 0x83, 0xe4, 0x33, 0x66, 0xe3, 0x0f, 0x9d, 0xcf, 0xac, 0xca, 0xf7, 0xee,
	0xe3, 0xbf, 0x1d, 0xb8, 0x9d, 0xa3, 0xe0, 0x9f, 0x43, 0x43, 0x71, 0x8a, 0x9d, 0xa5, 0xb0, 0x89,
	0x89, 0x2d, 0xbe, 0x49, 0xd8, 0x2c, 0x33, 0x7e, 0x06, 0x4d, 0xbd, 0x54, 0xd9, 0x22, 0x35, 0x29,
	0xbf, 0x5d, 0x90, 0x57, 0xdf, 0x25, 0x86, 0x29, 0x94, 0xb5, 0x21, 0x66, 0x63, 0x32, 0x57, 0x62,
	0x43, 0xcc, 0xc6, 0x79, 0x1b, 0x62, 0x36, 0xc6, 0xbb, 0x00, 0x3c, 0xf6, 0xfa, 0xef, 0xe2, 0xc8,
	0xeb, 0x33, 0x32, 0xdf, 0x71, 0xf6, 0x97, 0x68, 0x86, 0xe2, 0x7e, 0x09, 0x75, 0x6d, 0x3c, 0xc6,
	0x30, 0x1f, 0x78, 0xd7, 0x4c, 0x3a, 0xb9, 0x44, 0xe5, 0x6f, 0xdc, 0x86, 0xfa, 0x95, 0x3f, 0x62,
	0x67, 0x82, 0x5e, 0x93, 0xf4, 0x74, 0x2d, 0xbe, 0xf9, 0xfc, 0x99, 0xe7, 0x8f, 0xd8, 0x40, 0x1a,
	0x55, 0xa7, 0xe9, 0x5a, 0x60, 0xc5, 0xde, 0x90, 0x93, 0xf9, 0xce, 0x9c, 0xc0, 0x12, 0xbf, 0x5d,
	0x0a, 0xcb, 0x59, 0x47, 0xcb, 0xf4, 0xa5, 0x98, 0xb5, 0x12, 0xcc, 0xb9, 0x0c, 0xe6, 0x5f, 0x1c,
	0xa8, 0x6b, 0xcf, 0xf1, 0x63, 0x98, 0xe7, 0x22, 0x42, 0x49, 0x96, 0x5c, 0xfb, 0x0e, 0x60, 0x82,
	0x5d, 0xed, 0x21, 0x2a, 0xf9, 0x2b, 0x95, 0xea, 0x00, 0x5e, 0xca, 0x00, 0xce, 0x65, 0x02, 0x28,
	0x29, 0xd8, 0x85, 0x65, 0x16, 0x45, 0x61, 0xf4, 0x32, 0xd1, 0xa2, 0x42, 0x9c, 0xa3, 0xb9, 0xff,
	0x74, 0x00, 0x17, 0x95, 0xe3, 0x87, 0xb0, 0xe2, 0xf5, 0xe3, 0x89, 0x37, 0x12, 0xc4, 0x4b, 0xf6,
	0x6d, 0xac, 0x22, 0x61, 0x50, 0x05, 0xdf, 0xd8, 0x8b, 0x38, 0x1b, 0xa4, 0x7c, 0x49, 0x26, 0x0c,
	0x2a, 0xde, 0x87, 0x26, 0x57, 0xf1, 0x15, 0xc6, 0xfb, 0xc1, 0x50, 0xa5, 0xc5, 0x24, 0xe3, 0x9f,
	0x01, 0x8c, 0xbd, 0xc8, 0xbb, 0x66, 0x31, 0x8b, 0x92, 0x1c, 0x35, 0x0e, 0xb7, 0x0a, 0x57, 0x98,
	0xe6, 0xa0, 0x19, 0x66, 0xf7, 0xcf, 0x0e, 0xac, 0x09, 0x8d, 0x9f, 0x7a, 0x23, 0x7f, 0xe0, 0xc5,
	0x4c, 0x3b, 0xd3, 0x86, 0x3a, 0xcf, 0xbb, 0x91, 0xae, 0xf1, 0x01, 0xe0, 0x60, 0x72, 0xfd, 0x86,
	0x45, 0xe7, 0x57, 0xbd, 0xa9, 0x5a, 0xe1, 0xc4, 0x2d, 0x6a, 0xf9, 0x82, 0x7f, 0x01, 0x4b, 0x3c,
	0x51, 0x31, 0x61, 0x6a, 0xbb, 0xef, 0x5a, 0x2f, 0xd8, 0x0b, 0xcd, 0x45, 0xa7, 0x02, 0xee, 0x9f,
	0x6a, 0xd0, 0xca, 0x5b, 0xa8, 0x6e, 0x6f, 0x02, 0x8b, 0x3e, 0x97, 0x54, 0x69, 0x61, 0x9d, 0xea,
	0x65, 0x21, 0x89, 0xb5, 0x62, 0x12, 0xf1, 0x29, 0x2c, 0xc9, 0xf5, 0xe5, 0x6f, 0xc7, 0x89, 0x51,
	0x2b, 0x87, 0x07, 0xb6, 0x33, 0x68, 0xaa, 0x3d, 0xe8, 0x6a, 0x29, 0x3a, 0x05, 0x90, 0xdb, 0x6a,
	0x32, 0x1c, 0x32, 0x2e, 0x2a, 0x4d, 0x7a, 0x2e, 0x53, 0x8a, 0xfb, 0x09, 0x2c, 0xa5, 0x72, 0x78,
	0x0f, 0x76, 0x2e, 0x2e, 0xbb, 0xbd, 0xd7, 0x27, 0x2f, 0x7b, 0xa7, 0xdd, 0x97, 0xdd, 0xb3, 0xcb,
	0x27, 0x97, 0x27, 0xe7, 0x67, 0xaf, 0xcf, 0xce, 0x2f, 0x5f, 0x3f, 0x3b, 0x7f, 0x75, 0x76, 0x8c,
	0x3e, 0x12, 0x2c, 0xc7, 0xaf, 0x7a, 0xa7, 0x27, 0x47, 0x4f, 0x2e, 0xbb, 0xaf, 0x2d, 0xcc, 0xc8,
	0x71, 0x3f, 0x87, 0xd6, 0xc5, 0xc4, 0x8f, 0x99, 0xd1, 0x95, 0xe0, 0xa7, 0xd0, 0xe0, 0x82, 0x9e,
	0x6b, 0x68, 0x3a, 0xf6, 0x78, 0x4f, 0xf9, 0x68, 0x56, 0xc8, 0xc5, 0x80, 0x84, 0xef, 0xa2, 0x2c,
	0xa4, 0x7d, 0xd4, 0x23, 0x58, 0xcd, 0xd0, 0x54, 0x0e, 0x5a, 0x70, 0x4b, 0x64, 0x8a, 0x13, 0x47,
	0x1e, 0xe2, 0x64, 0xe1, 0xee, 0xc2, 0xb6, 0xae, 0x0c, 0xc7, 0x5e, 0xec, 0x5d, 0xc4, 0x61, 0xc4,
	0x4e, 0x02, 0x3f, 0xd6, 0x50, 0x6d, 0x20, 0xa2, 0x4a, 0x59, 0xbf, 0xdd, 0x81, 0x2d, 0x69, 0x96,
	0xf5, 0xe3, 0xaf, 0x61, 0x35, 0xdd, 0x57, 0xbd, 0x90, 0xfb, 0xc2, 0x6d, 0xdc, 0x81, 0x46, 0x38,
	0x1a, 0xe8, 0xa5, 0x74, 0xf8, 0x16, 0xcd, 0x92, 0x04, 0x47, 0xc0, 0xbe, 0x49, 0x39, 0x92, 0x9d,
	0x9a, 0x25, 0xb9, 0xbf, 0xaf, 0x41, 0x93, 0xb2, 0x2b, 0xaf, 0x1f, 0x87, 0x91, 0x3e, 0x02, 0x4f,
	0x61, 0x39, 0x1c, 0x0d, 0xd2, 0x3d, 0xa9, 0x22, 0x39, 0x6b, 0xe7, 0xe6, 0x64, 0x04, 0x46, 0xc0,
	0xbe, 0x99, 0x62, 0xd4, 0x6e, 0x86, 0x91, 0x95, 0xc1, 0x27, 0xb2, 0x5e, 0x78, 0xd7, 0xda, 0xd8,
	0xa4, 0x62, 0x36, 0x0e, 0xf7, 0x4a, 0x4f, 0xb8, 0xe6, 0xa4, 0x86, 0xa0, 0x08, 0x04, 0xf7, 0xbe,
	0x66, 0x47, 0x6f, 0xbd, 0x60, 0xc8, 0xb8, 0xdc, 0xa7, 0x75, 0x9a, 0x25, 0xb9, 0x2f, 0xa0, 0xf1,
	0xcc, 0x1f, 0xe9, 0x65, 0xee, 0xbe, 0x70, 0x8c, 0xfb, 0xa2, 0x03, 0x0d, 0xf1, 0xfb, 0x28, 0x0c,
	0x62, 0x16, 0xe8, 0x22, 0x96, 0x25, 0xb9, 0x7f, 0x75, 0x00, 0x4d, 0xa3, 0x3a, 0x3d, 0xb6, 0x7c,
	0xd2, 0x17, 0x1d, 0xba, 0x3e, 0xb6, 0x6a, 0x29, 0x36, 0x93, 0x3c, 0x51, 0x0a, 0x2a, 0x59, 0x88,
	0xc3, 0x2c, 0x30, 0x79, 0x62, 0xd2, 0x40, 0x5d, 0x17, 0x39, 0x1a, 0xfe, 0xa5, 0x32, 0x25, 0xf5,
	0x4b, 0xc4, 0xe7, 0x8e, 0x19, 0x9f, 0x8c, 0x63, 0x34, 0xcb, 0xef, 0xfe, 0x10, 0x9a, 0x7a, 0x6b,
	0xeb, 0xe4, 0x6f, 0x67, 0x6b, 0x56, 0xe2, 0x79, 0xa6, 0x26, 0xfd, 0xc3, 0x99, 0x1e, 0x90, 0xd4,
	0xb1, 0xfb, 0x70, 0xdb, 0xe7, 0x82, 0xda, 0x8b, 0x18, 0x17, 0x11, 0x49, 0xdc, 0xcb, 0x13, 0x75,
	0x61, 0x55, 0x37, 0xf0, 0x9c, 0x2e, 0xac, 0xfa, 0x06, 0x7e, 0xeb, 0xf1, 0x27, 0x23, 0xdf, 0xe3,
	0xfa, 0x06, 0xd6, 0xeb, 0x5c, 0x26, 0xe6, 0x8d, 0x4c, 0xec, 0xc3, 0x3c, 0x1f, 0x7b, 0x01, 0xb9,
	0x25, 0x77, 0x57, 0xab, 0xd8, 0xce, 0x78, 0x01, 0x95, 0x1c, 0xee, 0x63, 0x68, 0xbf, 0x0a, 0xf8,
	0x64, 0x3c, 0x0e, 0xa3, 0x98, 0x0d, 0x54, 0x2d, 0xcc, 0xa6, 0x46, 0x09, 0x29, 0x97, 0xf5, 0xd2,
	0xfd, 0xaf, 0x03, 0xe8, 0xc8, 0xeb, 0xbf, 0x65, 0x22, 0x86, 0x3a, 0x46, 0x04, 0x16, 0xfb, 0x2a,
	0xf9, 0x8a, 0x5d, 0x2d, 0xb5, 0xb1, 0x3d, 0x2f, 0x7e, 0x9b, 0x6d, 0x33, 0xc4, 0x3a, 0xb9, 0x9d,
	0x8f, 0x46, 0x21, 0xcf, 0xb6, 0x19, 0xc9, 0x1a, 0x1f, 0xc1, 0x02, 0x97, 0x23, 0x9a, 0x74, 0x71,
	0xe5, 0xf0, 0x7b, 0xa6, 0x2b, 0xa6, 0x0d, 0x32, 0xa7, 0x6a, 0xaa, 0x53, 0xa2, 0xee, 0x0b, 0x80,
	0x29, 0x15, 0x37, 0x60, 0xf1, 0xe8, 0x57, 0x4f, 0xce, 0x9e, 0x77, 0x45, 0x59, 0x05, 0x58, 0x38,
	0x3a, 0x3d, 0xbf, 0xe8, 0x1e, 0x23, 0x47, 0x7e, 0xa0, 0xdd, 0x27, 0x97, 0xdd, 0x63, 0x54, 0x13,
	0x8b, 0xe3, 0xee, 0x69, 0x57, 0x2c, 0xe6, 0x04, 0xd7, 0x79, 0xaf, 0x7b, 0xd6, 0x3d, 0x46, 0xf3,
	0xee, 0x61, 0x72, 0xf9, 0xa4, 0x47, 0x28, 0x73, 0x3f, 0xa6, 0x1e, 0x3a, 0x79, 0x0f, 0xdd, 0x7f,
	0x39, 0xb0, 0x6e, 0x08, 0xa9, 0x00, 0x7f, 0x06, 0xb7, 0x79, 0xf6, 0x83, 0x2c, 0x9b, 0x8d, 0xc3,
	0x43, 0xdb, 0xc5, 0x53, 0x90, 0xce, 0x51, 0x69, 0x1e, 0xc8, 0x7e, 0x76, 0xda, 0x9f, 0xc2, 0x72,
	0x56, 0xa8, 0x7a, 0x57, 0xa7, 0xdb, 0xa8, 0x36, 0x73, 0x1b, 0x3d, 0x84, 0xfb, 0x27, 0xd7, 0xe3,
	0x11, 0xbb, 0x66, 0x41, 0xec, 0x09, 0x64, 0x11, 0xf0, 0xe7, 0xa3, 0xf0, 0x4d, 0xcf, 0x8b, 0x63,
	0x16, 0x05, 0xba, 0x5e, 0xbf, 0x80, 0x07, 0x33, 0xf8, 0x54, 0x60, 0x5c, 0x58, 0x1e, 0x4e, 0xc9,
	0xfa, 0x3a, 0xc9, 0xd1, 0xdc, 0xbb, 0xb0, 0x53, 0x04, 0x3b, 0xf5, 0x79, 0x7a, 0x3b, 0x7c, 0x0e,
	0xbb, 0x65, 0x0c, 0x4a, 0xcd, 0x4f, 0x61, 0xd3, 0x2f, 0x70, 0x88, 0x9c, 0x69, 0x8d, 0x65, 0x9f,
	0xdd, 0x6b, 0xd8, 0xb9, 0x88, 0x27, 0x6f, 0xf2, 0xf8, 0x47, 0xe1, 0x20, 0x3d, 0x0c, 0x8f, 0x61,
	0xc3, 0x2e, 0xab, 0xe2, 0x5c, 0xf2, 0x55, 0x24, 0xae, 0x1f, 0x0e, 0x18, 0x57, 0xc5, 0x20, 0x59,
	0xb8, 0x67, 0x50, 0x17, 0xad, 0xd6, 0xb1, 0x7f, 0x75, 0x95, 0xa6, 0xc5, 0x99, 0x95, 0x96, 0xec,
	0x81, 0xac, 0xe5, 0x0e, 0xa4, 0xfb, 0x05, 0xd4, 0x85, 0x46, 0x89, 0x57, 0xb1, 0x75, 0xf1, 0x63,
	0x58, 0x8a, 0x95, 0xde, 0xc4, 0x22, 0xcb, 0x64, 0xa2, 0x0d, 0xa3, 0x53, 0x56, 0xf7, 0x6f, 0x7b,
	0xb0, 0xa8, 0x3b, 0xab, 0x2e, 0x34, 0x14, 0xaf, 0xec, 0xad, 0x1c, 0x79, 0x92, 0xef, 0x99, 0x28,
	0x8a, 0x5b, 0xff, 0x2b, 0x1b, 0xaa, 0xac, 0x9c, 0xd8, 0xab, 0x6a, 0x79, 0x92, 0xb4, 0xf1, 0x73,
	0x74, 0x4a, 0xc0, 0x03, 0x20, 0xac, 0x64, 0x74, 0x55, 0x2d, 0xe6, 0x7e, 0xe9, 0xc4, 0x68, 0xf0,
	0xd3, 0x52, 0x24, 0x3c, 0x86, 0x6d, 0x5e, 0xf1, 0xe8, 0x21, 0xab, 0x54, 0xe3, 0xf0, 0xfb, 0xb6,
	0xf9, 0xb1, 0x54, 0x5b, 0x25, 0x22, 0xfe, 0x12, 0xda, 0xbc, 0xf4, 0xcd, 0x43, 0x15, 0xf8, 0xef,
	0x56, 0xea, 0xcb, 0x49, 0xd0, 0x0a, 0x34, 0xfc, 0x3b, 0xe8, 0xf0, 0x19, 0xcf, 0x1d, 0x64, 0x41,
	0x6a, 0xfc, 0x51, 0xd9, 0x84, 0x5b, 0xea, 0xe5, 0x4c, 0x64, 0xfc, 0x35, 0xec, 0xf2, 0xca, 0x57,
	0x0f, 0xb2, 0x28, 0x75, 0x1f, 0xcc, 0xd4, 0x9d, 0xf7, 0x78, 0x06, 0xaa, 0xcc, 0x69, 0xc5, 0xc3,
	0x07, 0xa9, 0x97, 0xe4, 0xb4, 0x42, 0x86, 0x56, 0x22, 0xca, 0x9c, 0x96, 0xbe, 0x7b, 0x90, 0xa5,
	0x92, 0x9c, 0x96, 0x4a, 0xd0, 0x0a, 0x34, 0x4c, 0x01, 0xb3, 0xc2, 0x68, 0x4a, 0xe0, 0xc6, 0x13,
	0xb4, 0x45, 0x1a, 0x7f, 0x01, 0x1b, 0xcc, 0x6e, 0x7b, 0x43, 0xe2, 0x3e, 0x2c, 0x3d, 0x69, 0x79,
	0xbb, 0x4b, 0x50, 0xf0, 0x2b, 0x58, 0xe3, 0xc5, 0x11, 0x94, 0x2c, 0x4b, 0xf0, 0x7b, 0xd5, 0x43,
	0x59, 0x82, 0x6c, 0x93, 0xc7, 0x9f, 0x41, 0x8b, 0x5b, 0x06, 0x38, 0x72, 0xdb, 0xfe, 0xc4, 0x6b,
	0x1b, 0xf6, 0xa8, 0x15, 0x01, 0x7b, 0xb0, 0xc9, 0xec, 0x4f, 0xca, 0x64, 0x45, 0x82, 0x7f, 0xa7,
	0xaa, 0xf6, 0x64, 0xd8, 0x69, 0x19, 0x0e, 0x3e, 0x05, 0xc4, 0x8d, 0x09, 0x8c, 0x34, 0xed, 0xa3,
	0x9c, 0x39, 0xa9, 0xd1, 0x82, 0x24, 0x3e, 0x87, 0x55, 0x6e, 0xce, 0x6e, 0x04, 0x49, 0xb8, 0xbd,
	0x0a, 0x38, 0x65, 0x64, 0x51, 0x56, 0xc6, 0xd6, 0x32, 0x7c, 0x92, 0xd5, 0x92, 0xd8, 0x5a, 0x78,
	0xa9, 0x15, 0x41, 0x6c, 0xe0, 0x77, 0x85, 0x47, 0x7c, 0x82, 0xed, 0x1b, 0xb8, 0xf8, 0xdc, 0x4f,
	0x2d, 0xd2, 0xf2, 0xc8, 0x57, 0xcc, 0xa3, 0x64, 0xad, 0xe4, 0xc8, 0x57, 0xc8, 0xd0, 0x4a, 0x44,
	0x71, 0x3d, 0xf1, 0x92, 0x09, 0x97, 0xb4, 0xec, 0xd7, 0x53, 0xd9, 0x44, 0x4c, 0x4b, 0x91, 0xf0,
	0x10, 0xb6, 0x78, 0xd9, 0xac, 0x4c, 0xd6, 0xa5, 0x9a, 0x47, 0xd6, 0x54, 0x58, 0xf5, 0x94, 0x63,
	0xe1, 0x13, 0x68, 0xf2, 0xfc, 0x80, 0x44, 0x36, 0x24, 0xfc, 0xdd, 0xb2, 0xdd, 0xa3, 0x41, 0x4d,
	0xb9, 0xec, 0xc6, 0x4e, 0x77, 0xe2, 0x66, 0xf5, 0xc6, 0x4e, 0x37, 0x62, 0x41, 0x52, 0x18, 0x16,
	0xe5, 0xc7, 0x76, 0x42, 0xec, 0x86, 0x19, 0xd3, 0x3d, 0x35, 0xe5, 0x84, 0x61, 0x91, 0x31, 0xab,
	0x92, 0x2d, 0xbb, 0x61, 0xe6, 0x4c, 0x4b, 0x0b, 0x92, 0xa2, 0xe6, 0x4f, 0x4a, 0x07, 0x2d, 0xd2,
	0xb6, 0xd7, 0xfc, 0xf2, 0xd1, 0x8c, 0x56, 0xa0, 0x09, 0xcb, 0xfb, 0xc6, 0x5c, 0x44, 0xee, 0xd8,
	0x2d, 0x37, 0xe7, 0x27, 0x5a, 0x90, 0xd4, 0x65, 0xd3, 0x9c, 0x78, 0xc8, 0x76, 0x79, 0xd9, 0x34,
	0x79, 0xa9, 0x15, 0x01, 0xff, 0x06, 0xd6, 0xb9, 0x6d, 0xb0, 0x21, 0x3b, 0x12, 0xfa, 0xc1, 0x8d,
	0xa6, 0x20, 0x6a, 0xc7, 0xc0, 0x1c, 0x76, 0xfc, 0xaa, 0xe9, 0x80, 0xec, 0x4a, 0x25, 0x3f, 0x30,
	0x95, 0x54, 0x8e, 0x14, 0xb4, 0x1a, 0x53, 0xf4, 0x30, 0x7e, 0xe5, 0xc4, 0x41, 0xee, 0xda, 0x7b,
	0x98, 0xea, 0x39, 0x85, 0xce, 0x40, 0x15, 0xce, 0xf2, 0xaa, 0x69, 0x84, 0x74, 0xec, 0xce, 0x56,
	0x8e, 0x30, 0xb4, 0x1a, 0x13, 0x7f, 0x9c, 0xcc, 0x0d, 0xa2, 0xe1, 0x27, 0x7b, 0xf6, 0xff, 0xb4,
	0xd0, 0x33, 0x06, 0x4d, 0x39, 0xf1, 0x1f, 0x1c, 0xb8, 0xef, 0xdf, 0x60, 0x56, 0x24, 0xae, 0x84,
	0xfc, 0x78, 0x76, 0xa4, 0x8a, 0xb2, 0xf4, 0x46, 0x1a, 0xf0, 0x1f, 0x1d, 0x78, 0xe0, 0xdf, 0x64,
	0x1c, 0x25, 0xf7, 0xa4, 0x2d, 0x3f, 0xf9, 0x3f, 0x6d, 0x51, 0xc9, 0xbb, 0x99, 0x0e, 0xf7, 0x3f,
	0x0b, 0xd0, 0xc8, 0x0c, 0x3f, 0x78, 0x1d, 0x56, 0x0b, 0x1d, 0x24, 0xfa, 0x08, 0x6f, 0xc1, 0xba,
	0x75, 0x9c, 0x40, 0x0e, 0xde, 0x84, 0x35, 0x4b, 0xe7, 0x8f, 0x6a, 0x78, 0x07, 0xb6, 0x4a, 0x1b,
	0x74, 0x34, 0x87, 0xef, 0xc0, 0x66, 0x49, 0x0f, 0x8d, 0xe6, 0xa5, 0x3e, 0x5b, 0x33, 0x8b, 0x6e,
	0x49, 0x7d, 0xc5, 0xce, 0x13, 0x2d, 0xe0, 0x26, 0x34, 0x32, 0xad, 0x24, 0x5a, 0xc4, 0x6b, 0xd0,
	0x34, 0xb9, 0xea, 0x5a, 0xdc, 0x68, 0xd3, 0xd0, 0x12, 0x26, 0xf6, 0x07, 0x7e, 0x04, 0xc2, 0xd2,
	0x92, 0xce, 0x09, 0x35, 0x70, 0xab, 0xf8, 0x48, 0x8d, 0x96, 0x45, 0x18, 0x0b, 0x1d, 0x0c, 0xba,
	0x8d, 0x37, 0x6c, 0x7f, 0x1b, 0x80, 0x56, 0xa4, 0x6e, 0x4b, 0x1b, 0x82, 0x9a, 0x32, 0x10, 0xb6,
	0x2b, 0x1e, 0x21, 0xa9, 0xc3, 0xbc, 0x93, 0xd1, 0xaa, 0xd0, 0x51, 0xbc, 0x5d, 0x11, 0x16, 0xd1,
	0x30, 0xae, 0x45, 0xb4, 0x96, 0xb5, 0x3e, 0x35, 0xb3, 0x25, 0x58, 0x8d, 0x8b, 0x0a, 0xad, 0x0b,
	0x56, 0xf3, 0xc6, 0x41, 0x1b, 0x78, 0xb7, 0xea, 0x29, 0x0f, 0x6d, 0x0a, 0x29, 0xb3, 0xda, 0x23,
	0xa2, 0x63, 0x6d, 0xd6, 0x66, 0xb4, 0xa5, 0x13, 0x5f, 0xa8, 0xac, 0xa8, 0x8d, 0xf7, 0x66, 0xbc,
	0xbc, 0xa0, 0x3b, 0xd8, 0x9d, 0xf5, 0xf6, 0x82, 0xb6, 0xe5, 0xff, 0x7b, 0x54, 0x55, 0x18, 0xb4,
	0x83, 0x97, 0xa7, 0xef, 0x14, 0x68, 0x17, 0xef, 0xdf, 0xec, 0x99, 0x09, 0xdd, 0xc5, 0x8f, 0x6e,
	0xf8, 0xd0, 0x84, 0x3a, 0x4f, 0x57, 0xff, 0x5e, 0x5b, 0x79, 0x2e, 0xcf, 0xb5, 0x8a, 0x19, 0x7f,
	0xb3, 0x20, 0xff, 0x7e, 0xe4, 0xc7, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x7c, 0x50, 0xd9,
	0x6d, 0x22, 0x00, 0x00,
}
