on: 
  push:
    branches: [master]

name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: publish benchmark
        uses: getgauge-contrib/auto_update_pr@master
