name: Npm deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: macos-latest
    steps:

      - name: Switch to $GITHUB_REF
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set gauge version
        run: |
          gauge_version=`git describe --abbrev=0 --tags | sed 's/[a-z\/]*//g'`
          echo "::set-env name=GAUGE_VERSION::$gauge_version"

      - name: Setup Git User
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Deploy npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd build/npm
          npm version $GAUGE_VERSION
          npm publish --access=public
